/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-R-RO.asn"
 */

#ifndef	_SequenceRecord_R_RO_H_
#define	_SequenceRecord_R_RO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-R-RO */
typedef struct SequenceRecord_R_RO {
	double	 real1;
	double	*real2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_R_RO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_R_RO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_R_RO_H_ */
#include <asn_internal.h>
