/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#include "SetRecord-ThirdExtension.h"

static asn_TYPE_member_t asn_MBR_d_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct d, e),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"e"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct d, f),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"f"
		},
	{ ATF_POINTER, 3, offsetof(struct d, g),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"g"
		},
	{ ATF_POINTER, 2, offsetof(struct d, h),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BMPString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"h"
		},
	{ ATF_POINTER, 1, offsetof(struct d, y),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"y"
		},
};
static ber_tlv_tag_t asn_DEF_d_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_d_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* e at 13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* f at 19 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* g at 15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* h at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 4, 0, 0 } /* y at 17 */
};
static uint8_t asn_MAP_d_mmap_5[(5 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6) | (0 << 5) | (0 << 4) | (0 << 3)
};
static asn_SET_specifics_t asn_SPC_d_specs_5 = {
	sizeof(struct d),
	offsetof(struct d, _asn_ctx),
	offsetof(struct d, _presence_map),
	asn_MAP_d_tag2el_5,
	5,	/* Count of tags in the map */
	asn_MAP_d_tag2el_5,	/* Same as above */
	5,	/* Count of tags in the CXER map */
	1,	/* Whether extensible */
	(unsigned int *)asn_MAP_d_mmap_5	/* Mandatory elements map */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_d_5 = {
	"d",
	"d",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_d_tags_5,
	sizeof(asn_DEF_d_tags_5)
		/sizeof(asn_DEF_d_tags_5[0]) - 1, /* 1 */
	asn_DEF_d_tags_5,	/* Same as above */
	sizeof(asn_DEF_d_tags_5)
		/sizeof(asn_DEF_d_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_d_5,
	5,	/* Elements count */
	&asn_SPC_d_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SetRecord_ThirdExtension_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_ThirdExtension, a),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"a"
		},
	{ ATF_POINTER, 3, offsetof(struct SetRecord_ThirdExtension, b),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"b"
		},
	{ ATF_POINTER, 2, offsetof(struct SetRecord_ThirdExtension, c),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"c"
		},
	{ ATF_POINTER, 1, offsetof(struct SetRecord_ThirdExtension, d),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_d_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"d"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_ThirdExtension, z),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"z"
		},
};
static ber_tlv_tag_t asn_DEF_SetRecord_ThirdExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SetRecord_ThirdExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* b at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* c at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* d at 13 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 4, 0, 0 } /* z at 21 */
};
static uint8_t asn_MAP_SetRecord_ThirdExtension_mmap_1[(5 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (1 << 3)
};
static asn_SET_specifics_t asn_SPC_SetRecord_ThirdExtension_specs_1 = {
	sizeof(struct SetRecord_ThirdExtension),
	offsetof(struct SetRecord_ThirdExtension, _asn_ctx),
	offsetof(struct SetRecord_ThirdExtension, _presence_map),
	asn_MAP_SetRecord_ThirdExtension_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SetRecord_ThirdExtension_tag2el_1,	/* Same as above */
	5,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SetRecord_ThirdExtension_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SetRecord_ThirdExtension = {
	"SetRecord-ThirdExtension",
	"SetRecord-ThirdExtension",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SetRecord_ThirdExtension_tags_1,
	sizeof(asn_DEF_SetRecord_ThirdExtension_tags_1)
		/sizeof(asn_DEF_SetRecord_ThirdExtension_tags_1[0]), /* 1 */
	asn_DEF_SetRecord_ThirdExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetRecord_ThirdExtension_tags_1)
		/sizeof(asn_DEF_SetRecord_ThirdExtension_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SetRecord_ThirdExtension_1,
	5,	/* Elements count */
	&asn_SPC_SetRecord_ThirdExtension_specs_1	/* Additional specs */
};

