/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "RealRef.asn"
 */

#ifndef	_RealRef_H_
#define	_RealRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RealRef */
typedef double	 RealRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RealRef;
asn_struct_free_f RealRef_free;
asn_struct_print_f RealRef_print;
asn_constr_check_f RealRef_constraint;
ber_type_decoder_f RealRef_decode_ber;
der_type_encoder_f RealRef_encode_der;
xer_type_decoder_f RealRef_decode_xer;
xer_type_encoder_f RealRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RealRef_H_ */
#include <asn_internal.h>
