
SOME-MODULE

DEFINITIONS IMPLICIT TAGS    ::=

BEGIN

SetOfSomeSetOfRecRef ::= SET OF SomeSetOfRecRef

SomeSetOfRecRef ::= SomeSetOfRec

SomeSetOfRec ::= SET OF SetOfSomeSetOfRecRef


END
