/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetOfSomeSetOfRecRef+SomeSetOfRecRef+SomeSetOfRec.asn"
 */

#ifndef	_SetOfSomeSetOfRecRef_H_
#define	_SetOfSomeSetOfRecRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SomeSetOfRec;

/* SetOfSomeSetOfRecRef */
typedef struct SetOfSomeSetOfRecRef {
	A_SET_OF(struct SomeSetOfRec) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfSomeSetOfRecRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfSomeSetOfRecRef;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SomeSetOfRecRef.h"

#endif	/* _SetOfSomeSetOfRecRef_H_ */
#include <asn_internal.h>
