/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetOfSomeSetOfRecRef+SomeSetOfRecRef+SomeSetOfRec.asn"
 */

#ifndef	_SomeSetOfRecRef_H_
#define	_SomeSetOfRecRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SomeSetOfRec.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SomeSetOfRecRef */
typedef SomeSetOfRec_t	 SomeSetOfRecRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SomeSetOfRecRef;
asn_struct_free_f SomeSetOfRecRef_free;
asn_struct_print_f SomeSetOfRecRef_print;
asn_constr_check_f SomeSetOfRecRef_constraint;
ber_type_decoder_f SomeSetOfRecRef_decode_ber;
der_type_encoder_f SomeSetOfRecRef_encode_der;
xer_type_decoder_f SomeSetOfRecRef_decode_xer;
xer_type_encoder_f SomeSetOfRecRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SomeSetOfRecRef_H_ */
#include <asn_internal.h>
