/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-UT-UTO-UTRefWithTag-UTRefWithTagO+UtcTimeRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO_H_
#define	_SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTCTime.h>
#include "UtcTimeRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-UT-UTO-UTRefWithTag-UTRefWithTagO */
typedef struct SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO {
	struct seq {
		UTCTime_t	 time1;
		UTCTime_t	*time2	/* OPTIONAL */;
		UtcTimeRefWithTag_t	 time3;
		UtcTimeRefWithTag_t	*time4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_UT_UTO_UTRefWithTag_UTRefWithTagO_H_ */
#include <asn_internal.h>
