/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-UT-UTO-UTRefWithTag-UTRefWithTagO+UtcTimeRefWithTag.asn"
 */

#ifndef	_UtcTimeRefWithTag_H_
#define	_UtcTimeRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTCTime.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTimeRefWithTag */
typedef UTCTime_t	 UtcTimeRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UtcTimeRefWithTag;
asn_struct_free_f UtcTimeRefWithTag_free;
asn_struct_print_f UtcTimeRefWithTag_print;
asn_constr_check_f UtcTimeRefWithTag_constraint;
ber_type_decoder_f UtcTimeRefWithTag_decode_ber;
der_type_encoder_f UtcTimeRefWithTag_encode_der;
xer_type_decoder_f UtcTimeRefWithTag_decode_xer;
xer_type_encoder_f UtcTimeRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTimeRefWithTag_H_ */
#include <asn_internal.h>
