/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ES+SequenceRecord-I.asn"
 */

#ifndef	_SequenceRecord_ES_H_
#define	_SequenceRecord_ES_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SequenceRecord-I.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-ES */
typedef struct SequenceRecord_ES {
	SequenceRecord_I_t	 type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ES_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ES;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_ES_H_ */
#include <asn_internal.h>
