/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-BSD-BS-BSD-BSD.asn"
 */

#ifndef	_SequenceRecord_BSD_BS_BSD_BSD_H_
#define	_SequenceRecord_BSD_BS_BSD_BSD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BMPString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-BSD-BS-BSD-BSD */
typedef struct SequenceRecord_BSD_BS_BSD_BSD {
	BMPString_t	*val1	/* DEFAULT 12"3 */;
	BMPString_t	 val2;
	BMPString_t	*val3	/* DEFAULT 567 */;
	BMPString_t	*val4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_BSD_BS_BSD_BSD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_BSD_BS_BSD_BSD;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_BSD_BS_BSD_BSD_H_ */
#include <asn_internal.h>
