/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-UniS-UniSO-UniSRefWithTag-UniSRefWithTagO+UniversalStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO_H_
#define	_SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include "UniversalStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-UniS-UniSO-UniSRefWithTag-UniSRefWithTagO */
typedef struct SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO {
	struct seq {
		UniversalString_t	 str1;
		UniversalString_t	*str2	/* OPTIONAL */;
		UniversalStringRefWithTag_t	 str3;
		UniversalStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_UniS_UniSO_UniSRefWithTag_UniSRefWithTagO_H_ */
#include <asn_internal.h>
