/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-UniS-UniSO-UniSRefWithTag-UniSRefWithTagO+UniversalStringRefWithTag.asn"
 */

#ifndef	_UniversalStringRefWithTag_H_
#define	_UniversalStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UniversalStringRefWithTag */
typedef UniversalString_t	 UniversalStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UniversalStringRefWithTag;
asn_struct_free_f UniversalStringRefWithTag_free;
asn_struct_print_f UniversalStringRefWithTag_print;
asn_constr_check_f UniversalStringRefWithTag_constraint;
ber_type_decoder_f UniversalStringRefWithTag_decode_ber;
der_type_encoder_f UniversalStringRefWithTag_encode_der;
xer_type_decoder_f UniversalStringRefWithTag_decode_xer;
xer_type_encoder_f UniversalStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UniversalStringRefWithTag_H_ */
#include <asn_internal.h>
