/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "BitStringEnumeration.asn"
 */

#ifndef	_BitStringEnumeration_H_
#define	_BitStringEnumeration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BitStringEnumeration {
	BitStringEnumeration_value1	= 1000,
	BitStringEnumeration_value2	= 128,
	BitStringEnumeration_value3	= 937429
} e_BitStringEnumeration;

/* BitStringEnumeration */
typedef BIT_STRING_t	 BitStringEnumeration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BitStringEnumeration;
asn_struct_free_f BitStringEnumeration_free;
asn_struct_print_f BitStringEnumeration_print;
asn_constr_check_f BitStringEnumeration_constraint;
ber_type_decoder_f BitStringEnumeration_decode_ber;
der_type_encoder_f BitStringEnumeration_encode_der;
xer_type_decoder_f BitStringEnumeration_decode_xer;
xer_type_encoder_f BitStringEnumeration_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _BitStringEnumeration_H_ */
#include <asn_internal.h>
