/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-OSRef1-OSRef1O+OctetStringRef1+OctetStringRef2+OctetStringRef3+OctetStringRef4.asn"
 */

#ifndef	_OctetStringRef4_H_
#define	_OctetStringRef4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OctetStringRef4 */
typedef OCTET_STRING_t	 OctetStringRef4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OctetStringRef4;
asn_struct_free_f OctetStringRef4_free;
asn_struct_print_f OctetStringRef4_print;
asn_constr_check_f OctetStringRef4_constraint;
ber_type_decoder_f OctetStringRef4_decode_ber;
der_type_encoder_f OctetStringRef4_encode_der;
xer_type_decoder_f OctetStringRef4_decode_xer;
xer_type_encoder_f OctetStringRef4_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OctetStringRef4_H_ */
#include <asn_internal.h>
