/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-OSRef1-OSRef1O+OctetStringRef1+OctetStringRef2+OctetStringRef3+OctetStringRef4.asn"
 */

#ifndef	_OctetStringRef3_H_
#define	_OctetStringRef3_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OctetStringRef4.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OctetStringRef3 */
typedef OctetStringRef4_t	 OctetStringRef3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OctetStringRef3;
asn_struct_free_f OctetStringRef3_free;
asn_struct_print_f OctetStringRef3_print;
asn_constr_check_f OctetStringRef3_constraint;
ber_type_decoder_f OctetStringRef3_decode_ber;
der_type_encoder_f OctetStringRef3_encode_der;
xer_type_decoder_f OctetStringRef3_decode_xer;
xer_type_encoder_f OctetStringRef3_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OctetStringRef3_H_ */
#include <asn_internal.h>
