SOME-MODULE

DEFINITIONS AUTOMATIC TAGS    ::=

BEGIN

SequenceRecord-IO-I-I-Automatic    ::= SEQUENCE {
        type INTEGER OPTIONAL,
        type2 INTEGER,
        type3 INTEGER
}


END
