/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#ifndef	_SequenceRecord_ExtensionRootType_H_
#define	_SequenceRecord_ExtensionRootType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-ExtensionRootType */
typedef struct SequenceRecord_ExtensionRootType {
	long	 a;
	long	 b;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ExtensionRootType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ExtensionRootType;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_ExtensionRootType_H_ */
#include <asn_internal.h>
