/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ED-E-ED-ED.asn"
 */

#ifndef	_SequenceRecord_ED_E_ED_ED_H_
#define	_SequenceRecord_ED_E_ED_ED_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
//typedef enum val1 {
//} e_val1;
//typedef enum val2 {
//} e_val2;
//typedef enum val3 {
//} e_val3;
//typedef enum val4 {
//} e_val4;

/* SequenceRecord-ED-E-ED-ED */
typedef struct SequenceRecord_ED_E_ED_ED {
	long	*val1	/* DEFAULT 123 */;
	long	 val2;
	long	 val3	/* DEFAULT 0 */;
	long	*val4	/* DEFAULT 567 */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ED_E_ED_ED_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_val1_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_val2_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_val3_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_val4_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ED_E_ED_ED;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_ED_E_ED_ED_H_ */
#include <asn_internal.h>
