/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-NumS-NumSO-NumSRefWithTag-NumSRefWithTagO+NumericStringRefWithTag.asn"
 */

#ifndef	_NumericStringRefWithTag_H_
#define	_NumericStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumericStringRefWithTag */
typedef NumericString_t	 NumericStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumericStringRefWithTag;
asn_struct_free_f NumericStringRefWithTag_free;
asn_struct_print_f NumericStringRefWithTag_print;
asn_constr_check_f NumericStringRefWithTag_constraint;
ber_type_decoder_f NumericStringRefWithTag_decode_ber;
der_type_encoder_f NumericStringRefWithTag_encode_der;
xer_type_decoder_f NumericStringRefWithTag_decode_xer;
xer_type_encoder_f NumericStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumericStringRefWithTag_H_ */
#include <asn_internal.h>
