/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-NumS-NumSO-NumSRefWithTag-NumSRefWithTagO+NumericStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO_H_
#define	_SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>
#include "NumericStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-NumS-NumSO-NumSRefWithTag-NumSRefWithTagO */
typedef struct SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO {
	struct seq {
		NumericString_t	 str1;
		NumericString_t	*str2	/* OPTIONAL */;
		NumericStringRefWithTag_t	 str3;
		NumericStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_NumS_NumSO_NumSRefWithTag_NumSRefWithTagO_H_ */
#include <asn_internal.h>
