/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ISO-BSE-BSEO.asn"
 */

#include "SequenceRecord-ISO-BSE-BSEO.h"

static asn_TYPE_member_t asn_MBR_seq_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct seq, bitString1),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString1"
		},
	{ ATF_POINTER, 1, offsetof(struct seq, bitString2),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString2"
		},
};
static ber_tlv_tag_t asn_DEF_seq_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_seq_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 1 }, /* bitString1 at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, -1, 0 } /* bitString2 at 16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_seq_specs_2 = {
	sizeof(struct seq),
	offsetof(struct seq, _asn_ctx),
	asn_MAP_seq_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_seq_2 = {
	"seq",
	"seq",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_seq_tags_2,
	sizeof(asn_DEF_seq_tags_2)
		/sizeof(asn_DEF_seq_tags_2[0]), /* 1 */
	asn_DEF_seq_tags_2,	/* Same as above */
	sizeof(asn_DEF_seq_tags_2)
		/sizeof(asn_DEF_seq_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_seq_2,
	2,	/* Elements count */
	&asn_SPC_seq_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SequenceRecord_ISO_BSE_BSEO_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_ISO_BSE_BSEO, seq),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_seq_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"seq"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_ISO_BSE_BSEO_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* seq at 14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_ISO_BSE_BSEO_specs_1 = {
	sizeof(struct SequenceRecord_ISO_BSE_BSEO),
	offsetof(struct SequenceRecord_ISO_BSE_BSEO, _asn_ctx),
	asn_MAP_SequenceRecord_ISO_BSE_BSEO_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ISO_BSE_BSEO = {
	"SequenceRecord-ISO-BSE-BSEO",
	"SequenceRecord-ISO-BSE-BSEO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1,
	sizeof(asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_ISO_BSE_BSEO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_ISO_BSE_BSEO_1,
	1,	/* Elements count */
	&asn_SPC_SequenceRecord_ISO_BSE_BSEO_specs_1	/* Additional specs */
};

