/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "Choice-IChoicePS-IA5.asn"
 */

#ifndef	_Choice_IChoicePS_IA5_H_
#define	_Choice_IChoicePS_IA5_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice_IChoicePS_IA5_PR {
	Choice_IChoicePS_IA5_PR_NOTHING,	/* No components present */
	Choice_IChoicePS_IA5_PR_choice
} Choice_IChoicePS_IA5_PR;
typedef enum choice_PR {
	choice_PR_NOTHING,	/* No components present */
	choice_PR_str1,
	choice_PR_str2
} choice_PR;

/* Choice-IChoicePS-IA5 */
typedef struct Choice_IChoicePS_IA5 {
	Choice_IChoicePS_IA5_PR present;
	union Choice_IChoicePS_IA5_u {
		struct choice {
			choice_PR present;
			union Choice_IChoicePS_IA5__choice_u {
				PrintableString_t	 str1;
				IA5String_t	 str2;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} choice;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice_IChoicePS_IA5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice_IChoicePS_IA5;

#ifdef __cplusplus
}
#endif

#endif	/* _Choice_IChoicePS_IA5_H_ */
#include <asn_internal.h>
