/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_ChoiceT1choiceRef_H_
#define	_ChoiceT1choiceRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChoiceT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChoiceT1choiceRef */
typedef ChoiceT1_t	 ChoiceT1choiceRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT1choiceRef;
asn_struct_free_f ChoiceT1choiceRef_free;
asn_struct_print_f ChoiceT1choiceRef_print;
asn_constr_check_f ChoiceT1choiceRef_constraint;
ber_type_decoder_f ChoiceT1choiceRef_decode_ber;
der_type_encoder_f ChoiceT1choiceRef_encode_der;
xer_type_decoder_f ChoiceT1choiceRef_decode_xer;
xer_type_encoder_f ChoiceT1choiceRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT1choiceRef_H_ */
#include <asn_internal.h>
