/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags1"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_ChoiceT1_H_
#define	_ChoiceT1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceT1_PR {
	ChoiceT1_PR_NOTHING,	/* No components present */
	ChoiceT1_PR_first,
	ChoiceT1_PR_second
} ChoiceT1_PR;

/* ChoiceT1 */
typedef struct ChoiceT1 {
	ChoiceT1_PR present;
	union ChoiceT1_u {
		long	 first;
		long	 second;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceT1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT1;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT1_H_ */
#include <asn_internal.h>
