/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_ChoiceT2choice_H_
#define	_ChoiceT2choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChoiceT1.h"
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceT2choice_PR {
	ChoiceT2choice_PR_NOTHING,	/* No components present */
	ChoiceT2choice_PR_one,
	ChoiceT2choice_PR_two
} ChoiceT2choice_PR;

/* ChoiceT2choice */
typedef struct ChoiceT2choice {
	ChoiceT2choice_PR present;
	union ChoiceT2choice_u {
		ChoiceT1_t	 one;
		IA5String_t	 two;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceT2choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT2choice;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT2choice_H_ */
#include <asn_internal.h>
