/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#include "ChoiceT2choice.h"

static asn_TYPE_member_t asn_MBR_ChoiceT2choice_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceT2choice, choice.one),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ChoiceT1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"one"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceT2choice, choice.two),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"two"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChoiceT2choice_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* one at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* two at 30 */
};
static asn_CHOICE_specifics_t asn_SPC_ChoiceT2choice_specs_1 = {
	sizeof(struct ChoiceT2choice),
	offsetof(struct ChoiceT2choice, _asn_ctx),
	offsetof(struct ChoiceT2choice, present),
	sizeof(((struct ChoiceT2choice *)0)->present),
	asn_MAP_ChoiceT2choice_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChoiceT2choice = {
	"ChoiceT2choice",
	"ChoiceT2choice",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ChoiceT2choice_1,
	2,	/* Elements count */
	&asn_SPC_ChoiceT2choice_specs_1	/* Additional specs */
};

