/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_SequenceOfT2choice_H_
#define	_SequenceOfT2choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChoiceT1;

/* SequenceOfT2choice */
typedef struct SequenceOfT2choice {
	A_SEQUENCE_OF(struct ChoiceT1) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfT2choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfT2choice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChoiceT1.h"

#endif	/* _SequenceOfT2choice_H_ */
#include <asn_internal.h>
