/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_SequenceT2choice_H_
#define	_SequenceT2choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChoiceT1.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChoiceT1;

/* SequenceT2choice */
typedef struct SequenceT2choice {
	ChoiceT1_t	 one;
	struct ChoiceT1	*two	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceT2choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceT2choice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChoiceT1.h"

#endif	/* _SequenceT2choice_H_ */
#include <asn_internal.h>
