/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestTags2"
 * 	found in "ChoiceT1+SequenceT2choice+SetT2choice+ChoiceT2choice+SetOfT2choice+SequenceOfT2choice+ChoiceT1choiceRef.asn"
 */

#ifndef	_SetT2choice_H_
#define	_SetT2choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChoiceT1.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetT2choice_PR {
	SetT2choice_PR_one,	/* Member one is present */
	SetT2choice_PR_two,	/* Member two is present */
} SetT2choice_PR;

/* Forward declarations */
struct ChoiceT1;

/* SetT2choice */
typedef struct SetT2choice {
	ChoiceT1_t	 one;
	struct ChoiceT1	*two	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetT2choice, SetT2choice_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetT2choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetT2choice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChoiceT1.h"

#endif	/* _SetT2choice_H_ */
#include <asn_internal.h>
