/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ChoiceRecord_empty_H_
#define	_ChoiceRecord_empty_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceRecord_empty_PR {
	ChoiceRecord_empty_PR_NOTHING,	/* No components present */
	ChoiceRecord_empty_PR_int,
	ChoiceRecord_empty_PR_real
} ChoiceRecord_empty_PR;

/* ChoiceRecord-empty */
typedef struct ChoiceRecord_empty {
	ChoiceRecord_empty_PR present;
	union ChoiceRecord_empty_u {
		long	 Int;
		double	 real;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceRecord_empty_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceRecord_empty;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceRecord_empty_H_ */
#include <asn_internal.h>
