/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-OS-OSO-OSRef-OSRefO+OctetStringRef.asn"
 */

#ifndef	_SequenceRecord_OS_OSO_OSRef_OSRefO_H_
#define	_SequenceRecord_OS_OSO_OSRef_OSRefO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "OctetStringRef.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-OS-OSO-OSRef-OSRefO */
typedef struct SequenceRecord_OS_OSO_OSRef_OSRefO {
	OCTET_STRING_t	 octetString1;
	OCTET_STRING_t	*octetString2	/* OPTIONAL */;
	OctetStringRef_t	 octetString3;
	OctetStringRef_t	*octetString4	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_OS_OSO_OSRef_OSRefO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_OS_OSO_OSRef_OSRefO_H_ */
#include <asn_internal.h>
