/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-OS-OSO-OSRef-OSRefO+OctetStringRef.asn"
 */

#include "SequenceRecord-OS-OSO-OSRef-OSRefO.h"

static asn_TYPE_member_t asn_MBR_SequenceRecord_OS_OSO_OSRef_OSRefO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_OS_OSO_OSRef_OSRefO, octetString1),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString1"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_OS_OSO_OSRef_OSRefO, octetString2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_OS_OSO_OSRef_OSRefO, octetString3),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OctetStringRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString3"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_OS_OSO_OSRef_OSRefO, octetString4),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OctetStringRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString4"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_OS_OSO_OSRef_OSRefO_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 2 }, /* octetString1 at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -1, 1 }, /* octetString3 at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -2, 0 }, /* octetString4 at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* octetString2 at 10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_OS_OSO_OSRef_OSRefO_specs_1 = {
	sizeof(struct SequenceRecord_OS_OSO_OSRef_OSRefO),
	offsetof(struct SequenceRecord_OS_OSO_OSRef_OSRefO, _asn_ctx),
	asn_MAP_SequenceRecord_OS_OSO_OSRef_OSRefO_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO = {
	"SequenceRecord-OS-OSO-OSRef-OSRefO",
	"SequenceRecord-OS-OSO-OSRef-OSRefO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1,
	sizeof(asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_OS_OSO_OSRef_OSRefO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_OS_OSO_OSRef_OSRefO_1,
	4,	/* Elements count */
	&asn_SPC_SequenceRecord_OS_OSO_OSRef_OSRefO_specs_1	/* Additional specs */
};

