/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "OctetStringRef.asn"
 */

#ifndef	_OctetStringRef_H_
#define	_OctetStringRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OctetStringRef */
typedef OCTET_STRING_t	 OctetStringRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OctetStringRef;
asn_struct_free_f OctetStringRef_free;
asn_struct_print_f OctetStringRef_print;
asn_constr_check_f OctetStringRef_constraint;
ber_type_decoder_f OctetStringRef_decode_ber;
der_type_encoder_f OctetStringRef_encode_der;
xer_type_decoder_f OctetStringRef_decode_xer;
xer_type_encoder_f OctetStringRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OctetStringRef_H_ */
#include <asn_internal.h>
