/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-ISetO-I-IO-I.asn"
 */

#ifndef	_SetRecord_ISetO_I_IO_I_H_
#define	_SetRecord_ISetO_I_IO_I_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_ISetO_I_IO_I_PR {
	SetRecord_ISetO_I_IO_I_PR_set,	/* Member set is present */
} SetRecord_ISetO_I_IO_I_PR;

/*
 * Method of determining the components presence
 */
typedef enum set_PR {
	set_PR_type,	/* Member type is present */
	set_PR_type2,	/* Member type2 is present */
	set_PR_type3,	/* Member type3 is present */
} set_PR;

/* SetRecord-ISetO-I-IO-I */
typedef struct SetRecord_ISetO_I_IO_I {
	struct set {
		long	 type;
		long	*type2	/* OPTIONAL */;
		long	 type3;
		
		/* Presence bitmask: ASN_SET_ISPRESENT(pset, set_PR_x) */
		unsigned int _presence_map
			[((3+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *set;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_ISetO_I_IO_I, SetRecord_ISetO_I_IO_I_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_ISetO_I_IO_I_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_ISetO_I_IO_I;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_ISetO_I_IO_I_H_ */
#include <asn_internal.h>
