/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetOfInteger.asn"
 */

#ifndef	_SetOfInteger_H_
#define	_SetOfInteger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetOfInteger */
typedef struct SetOfInteger {
	A_SET_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfInteger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfInteger;

#ifdef __cplusplus
}
#endif

#endif	/* _SetOfInteger_H_ */
#include <asn_internal.h>
