#!/bin/sh

#
# This script is designed to quickly create lots of files in underlying
# test-* directories, do lots of other magic stuff and exit cleanly.
#

if [ "x$1" = "x" ]; then
	echo "Usage: $0 <check-NN.cpp>"
	exit
fi

check()
{
local testdir=$1
touch ${testdir}-FAILED		# Create this file to ease post mortem analysis

if [ ! -d $testdir ]; then
	mkdir $testdir		|| exit $?
fi
cd $testdir			|| exit $?
rm -f ./$source 2>/dev/null
ln -fns ../$source		|| exit $?

asn_module=`echo ../../../tests/${testno}-*.asn1`

# Create a Makefile for the project.
cat > Makefile <<EOM
# This file is autogenerated by ../$0

COMMON_FLAGS= -I.# -DEMIT_ASN_DEBUG
CXXFLAGS = \${COMMON_FLAGS} ${CXXFLAGS} -g -O0 -std=c++11 -U__STRICT_ANSI__

CXX ?= ${CXX}

all: check-executable
check-executable: compiled-module *.cpp
	@rm -f *.core
	\$(CXX) \$(CXXFLAGS) $3 -o check-executable *.cpp

# Compile the corresponding .asn1 spec.
compiled-module: ${asn_module} ../../asn1cpp
	../../asn1cpp -S ../../../skeletons -Wdebug-compiler	\\
		${AFLAGS} $2 ${asn_module}
	@touch compiled-module

check-succeeded: check-executable
	@rm -f check-succeeded
	./check-executable
	@touch check-succeeded

check: check-succeeded

clean:
	@rm -f *.o check-executable
EOM

# Perform building and checking
make check || exit $?


rm -f ../${testdir}-FAILED
}


# Compute the .asn1 spec name by the given file name.
source=`echo "$1" | sed -e 's/.*\///'`
testno=`echo "$source" | cut -f2 -d'-' | cut -f1 -d'.'`

args=`echo "$source" | sed -e 's/\.cpp*$//'`
testdir=test-${args}

OFS=$IFS
IFS="."
set $args
shift
IFS=$OFS
AFLAGS="$@"

check ${testdir}-secure-ptrs "" -DDEBUG
cd ..
check ${testdir}-secure-ptrs-no-switch -fno-switch -DDEBUG
cd ..
check ${testdir}-insecure-ptrs -finsecure-pointers "-DINSECURE_POINTERS -DDEBUG"
cd ..
check ${testdir}-insecure-ptrs-no-switch "-finsecure-pointers -fno-switch" "-DINSECURE_POINTERS -DDEBUG"
cd ..
check ${testdir}-secure-ptrs-ptr-choice-getters "-fptr-choice-getters" "-DDEBUG -DPTR_CHOICE_GETTERS"
cd ..

exit 0
