/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE1"
 * 	found in "External+ExternalASN.asn"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_External_H_
#define	_External_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <NativeInteger.h>
#include <ObjectDescriptor.h>
#include <ANY.h>
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum External__encoding_PR {
	External__encoding_PR_NOTHING,	/* No components present */
	External__encoding_PR_single_ASN1_type,
	External__encoding_PR_octet_aligned,
	External__encoding_PR_arbitrary
} External__encoding_PR;

/* External */
typedef struct External {
	OBJECT_IDENTIFIER_t	*direct_reference	/* OPTIONAL */;
	long	*indirect_reference	/* OPTIONAL */;
	ObjectDescriptor_t	*data_value_descriptor	/* OPTIONAL */;
	struct External__encoding {
		External__encoding_PR present;
		union External__encoding_u {
			ANY_t	 single_ASN1_type;
			OCTET_STRING_t	 octet_aligned;
			BIT_STRING_t	 arbitrary;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} encoding;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} External_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_External;

#ifdef __cplusplus
}
#endif

#endif	/* _External_H_ */
#include <asn_internal.h>
