/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-GenS-GenSO-GenSRefWithTag-GenSRefWithTagO+GenStringRefWithTag.asn"
 */

#ifndef	_GenStringRefWithTag_H_
#define	_GenStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GenStringRefWithTag */
typedef GeneralString_t	 GenStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenStringRefWithTag;
asn_struct_free_f GenStringRefWithTag_free;
asn_struct_print_f GenStringRefWithTag_print;
asn_constr_check_f GenStringRefWithTag_constraint;
ber_type_decoder_f GenStringRefWithTag_decode_ber;
der_type_encoder_f GenStringRefWithTag_encode_der;
xer_type_decoder_f GenStringRefWithTag_decode_xer;
xer_type_encoder_f GenStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GenStringRefWithTag_H_ */
#include <asn_internal.h>
