/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-GenS-GenSO-GenSRefWithTag-GenSRefWithTagO+GenStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO_H_
#define	_SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralString.h>
#include "GenStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-GenS-GenSO-GenSRefWithTag-GenSRefWithTagO */
typedef struct SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO {
	struct seq {
		GeneralString_t	 str1;
		GeneralString_t	*str2	/* OPTIONAL */;
		GenStringRefWithTag_t	 str3;
		GenStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_GenS_GenSO_GenSRefWithTag_GenSRefWithTagO_H_ */
#include <asn_internal.h>
