/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-VidS-VidSO-VidSRefWithTag-VidSRefWithTagO+VideotexStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO_H_
#define	_SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VideotexString.h>
#include "VideotexStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-VidS-VidSO-VidSRefWithTag-VidSRefWithTagO */
typedef struct SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO {
	struct seq {
		VideotexString_t	 str1;
		VideotexString_t	*str2	/* OPTIONAL */;
		VideotexStringRefWithTag_t	 str3;
		VideotexStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_VidS_VidSO_VidSRefWithTag_VidSRefWithTagO_H_ */
#include <asn_internal.h>
