/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-VidS-VidSO-VidSRefWithTag-VidSRefWithTagO+VideotexStringRefWithTag.asn"
 */

#include "VideotexStringRefWithTag.h"

int
VideotexStringRefWithTag_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_VideotexString.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using VideotexString,
 * so here we adjust the DEF accordingly.
 */
static void
VideotexStringRefWithTag_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_VideotexString.free_struct;
	td->print_struct   = asn_DEF_VideotexString.print_struct;
	td->ber_decoder    = asn_DEF_VideotexString.ber_decoder;
	td->der_encoder    = asn_DEF_VideotexString.der_encoder;
	td->xer_decoder    = asn_DEF_VideotexString.xer_decoder;
	td->xer_encoder    = asn_DEF_VideotexString.xer_encoder;
	td->uper_decoder   = asn_DEF_VideotexString.uper_decoder;
	td->uper_encoder   = asn_DEF_VideotexString.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_VideotexString.per_constraints;
	td->elements       = asn_DEF_VideotexString.elements;
	td->elements_count = asn_DEF_VideotexString.elements_count;
	td->specifics      = asn_DEF_VideotexString.specifics;
}

void
VideotexStringRefWithTag_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
VideotexStringRefWithTag_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
VideotexStringRefWithTag_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
VideotexStringRefWithTag_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
VideotexStringRefWithTag_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
VideotexStringRefWithTag_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	VideotexStringRefWithTag_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static ber_tlv_tag_t asn_DEF_VideotexStringRefWithTag_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (21 << 2))
};
asn_TYPE_descriptor_t asn_DEF_VideotexStringRefWithTag = {
	"VideotexStringRefWithTag",
	"VideotexStringRefWithTag",
	VideotexStringRefWithTag_free,
	VideotexStringRefWithTag_print,
	VideotexStringRefWithTag_constraint,
	VideotexStringRefWithTag_decode_ber,
	VideotexStringRefWithTag_encode_der,
	VideotexStringRefWithTag_decode_xer,
	VideotexStringRefWithTag_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VideotexStringRefWithTag_tags_1,
	sizeof(asn_DEF_VideotexStringRefWithTag_tags_1)
		/sizeof(asn_DEF_VideotexStringRefWithTag_tags_1[0]) - 1, /* 1 */
	asn_DEF_VideotexStringRefWithTag_tags_1,	/* Same as above */
	sizeof(asn_DEF_VideotexStringRefWithTag_tags_1)
		/sizeof(asn_DEF_VideotexStringRefWithTag_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	0	/* No specifics */
};

