/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-VidS-VidSO-VidSRefWithTag-VidSRefWithTagO+VideotexStringRefWithTag.asn"
 */

#ifndef	_VideotexStringRefWithTag_H_
#define	_VideotexStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VideotexString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VideotexStringRefWithTag */
typedef VideotexString_t	 VideotexStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VideotexStringRefWithTag;
asn_struct_free_f VideotexStringRefWithTag_free;
asn_struct_print_f VideotexStringRefWithTag_print;
asn_constr_check_f VideotexStringRefWithTag_constraint;
ber_type_decoder_f VideotexStringRefWithTag_decode_ber;
der_type_encoder_f VideotexStringRefWithTag_encode_der;
xer_type_decoder_f VideotexStringRefWithTag_decode_xer;
xer_type_encoder_f VideotexStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VideotexStringRefWithTag_H_ */
#include <asn_internal.h>
