/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SeqT1+SequenceT2Seq+SetT2seq+ChoiceT2seq+SetOfT2seq+SequenceOfT2seq+ChoiceT1seqRef.asn"
 */

#ifndef	_SeqT1seqRef_H_
#define	_SeqT1seqRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SeqT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SeqT1seqRef */
typedef SeqT1_t	 SeqT1seqRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqT1seqRef;
asn_struct_free_f SeqT1seqRef_free;
asn_struct_print_f SeqT1seqRef_print;
asn_constr_check_f SeqT1seqRef_constraint;
ber_type_decoder_f SeqT1seqRef_decode_ber;
der_type_encoder_f SeqT1seqRef_encode_der;
xer_type_decoder_f SeqT1seqRef_decode_xer;
xer_type_encoder_f SeqT1seqRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SeqT1seqRef_H_ */
#include <asn_internal.h>
