/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest1"
 * 	found in "SeqT1+SequenceT2Seq+SetT2seq+ChoiceT2seq+SetOfT2seq+SequenceOfT2seq+ChoiceT1seqRef.asn"
 */

#ifndef	_SeqT1_H_
#define	_SeqT1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SeqT1 */
typedef struct SeqT1 {
	long	 first;
	long	 second;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqT1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqT1;

#ifdef __cplusplus
}
#endif

#endif	/* _SeqT1_H_ */
#include <asn_internal.h>
