/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ChoiceRealInteger.asn"
 */

#include "ChoiceRealInteger.h"

static asn_TYPE_member_t asn_MBR_ChoiceRealInteger_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceRealInteger, choice.real),
		(ASN_TAG_CLASS_UNIVERSAL | (9 << 2)),
		0,
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"real"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceRealInteger, choice.integer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integer"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChoiceRealInteger_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* integer at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (9 << 2)), 0, 0, 0 } /* real at 9 */
};
static asn_CHOICE_specifics_t asn_SPC_ChoiceRealInteger_specs_1 = {
	sizeof(struct ChoiceRealInteger),
	offsetof(struct ChoiceRealInteger, _asn_ctx),
	offsetof(struct ChoiceRealInteger, present),
	sizeof(((struct ChoiceRealInteger *)0)->present),
	asn_MAP_ChoiceRealInteger_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChoiceRealInteger = {
	"ChoiceRealInteger",
	"ChoiceRealInteger",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ChoiceRealInteger_1,
	2,	/* Elements count */
	&asn_SPC_ChoiceRealInteger_specs_1	/* Additional specs */
};

