/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetOfT1+SequenceT2setof+SetT2setof+ChoiceT2setof+SetOfT2setof+SequenceOfT2setof+SetOfT1setofRef.asn"
 */

#ifndef	_SequenceT2setof_H_
#define	_SequenceT2setof_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetOfT1.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetOfT1;

/* SequenceT2setof */
typedef struct SequenceT2setof {
	SetOfT1_t	 one;
	struct SetOfT1	*two	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceT2setof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceT2setof;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetOfT1.h"

#endif	/* _SequenceT2setof_H_ */
#include <asn_internal.h>
