/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetOfT1+SequenceT2setof+SetT2setof+ChoiceT2setof+SetOfT2setof+SequenceOfT2setof+SetOfT1setofRef.asn"
 */

#ifndef	_SetOfT2setof_H_
#define	_SetOfT2setof_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetOfT1;

/* SetOfT2setof */
typedef struct SetOfT2setof {
	A_SET_OF(struct SetOfT1) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfT2setof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfT2setof;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetOfT1.h"

#endif	/* _SetOfT2setof_H_ */
#include <asn_internal.h>
