/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest1"
 * 	found in "SetOfT1+SequenceT2setof+SetT2setof+ChoiceT2setof+SetOfT2setof+SequenceOfT2setof+SetOfT1setofRef.asn"
 */

#ifndef	_SetOfT1_H_
#define	_SetOfT1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetOfT1 */
typedef struct SetOfT1 {
	A_SET_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfT1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfT1;

#ifdef __cplusplus
}
#endif

#endif	/* _SetOfT1_H_ */
#include <asn_internal.h>
