/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetOfT1+SequenceT2setof+SetT2setof+ChoiceT2setof+SetOfT2setof+SequenceOfT2setof+SetOfT1setofRef.asn"
 */

#ifndef	_SetOfT1setofRef_H_
#define	_SetOfT1setofRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetOfT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetOfT1setofRef */
typedef SetOfT1_t	 SetOfT1setofRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfT1setofRef;
asn_struct_free_f SetOfT1setofRef_free;
asn_struct_print_f SetOfT1setofRef_print;
asn_constr_check_f SetOfT1setofRef_constraint;
ber_type_decoder_f SetOfT1setofRef_decode_ber;
der_type_encoder_f SetOfT1setofRef_encode_der;
xer_type_decoder_f SetOfT1setofRef_decode_xer;
xer_type_encoder_f SetOfT1setofRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SetOfT1setofRef_H_ */
#include <asn_internal.h>
