/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetOfT1+SequenceT2setof+SetT2setof+ChoiceT2setof+SetOfT2setof+SequenceOfT2setof+SetOfT1setofRef.asn"
 */

#ifndef	_SetT2setof_H_
#define	_SetT2setof_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetOfT1.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetT2setof_PR {
	SetT2setof_PR_one,	/* Member one is present */
	SetT2setof_PR_two,	/* Member two is present */
} SetT2setof_PR;

/* Forward declarations */
struct SetOfT1;

/* SetT2setof */
typedef struct SetT2setof {
	SetOfT1_t	 one;
	struct SetOfT1	*two	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetT2setof, SetT2setof_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetT2setof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetT2setof;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetOfT1.h"

#endif	/* _SetT2setof_H_ */
#include <asn_internal.h>
