/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-2inner-seq.asn"
 */

#include "SequenceRecord-2inner-seq.h"

static asn_TYPE_member_t asn_MBR_level2_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct level2, value),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
};
static ber_tlv_tag_t asn_DEF_level2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_level2_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* value at 12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_level2_specs_3 = {
	sizeof(struct level2),
	offsetof(struct level2, _asn_ctx),
	asn_MAP_level2_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_level2_3 = {
	"level2",
	"level2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_level2_tags_3,
	sizeof(asn_DEF_level2_tags_3)
		/sizeof(asn_DEF_level2_tags_3[0]), /* 1 */
	asn_DEF_level2_tags_3,	/* Same as above */
	sizeof(asn_DEF_level2_tags_3)
		/sizeof(asn_DEF_level2_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_level2_3,
	1,	/* Elements count */
	&asn_SPC_level2_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_level1_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct level1, level2),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_level2_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"level2"
		},
};
static ber_tlv_tag_t asn_DEF_level1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_level1_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* level2 at 12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_level1_specs_2 = {
	sizeof(struct level1),
	offsetof(struct level1, _asn_ctx),
	asn_MAP_level1_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_level1_2 = {
	"level1",
	"level1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_level1_tags_2,
	sizeof(asn_DEF_level1_tags_2)
		/sizeof(asn_DEF_level1_tags_2[0]), /* 1 */
	asn_DEF_level1_tags_2,	/* Same as above */
	sizeof(asn_DEF_level1_tags_2)
		/sizeof(asn_DEF_level1_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_level1_2,
	1,	/* Elements count */
	&asn_SPC_level1_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SequenceRecord_2inner_seq_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_2inner_seq, level1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_level1_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"level1"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_2inner_seq_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_2inner_seq_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* level1 at 13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_2inner_seq_specs_1 = {
	sizeof(struct SequenceRecord_2inner_seq),
	offsetof(struct SequenceRecord_2inner_seq, _asn_ctx),
	asn_MAP_SequenceRecord_2inner_seq_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_2inner_seq = {
	"SequenceRecord-2inner-seq",
	"SequenceRecord-2inner-seq",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_2inner_seq_tags_1,
	sizeof(asn_DEF_SequenceRecord_2inner_seq_tags_1)
		/sizeof(asn_DEF_SequenceRecord_2inner_seq_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_2inner_seq_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_2inner_seq_tags_1)
		/sizeof(asn_DEF_SequenceRecord_2inner_seq_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_2inner_seq_1,
	1,	/* Elements count */
	&asn_SPC_SequenceRecord_2inner_seq_specs_1	/* Additional specs */
};

