/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-2inner-seq.asn"
 */

#ifndef	_SequenceRecord_2inner_seq_H_
#define	_SequenceRecord_2inner_seq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-2inner-seq */
typedef struct SequenceRecord_2inner_seq {
	struct level1 {
		struct level2 {
			long	 value;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} level2;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} level1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_2inner_seq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_2inner_seq;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_2inner_seq_H_ */
#include <asn_internal.h>
