/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetT1+SequenceT2Set+SetT2set+ChoiceT2set+SetOfT2set+SequenceOfT2set+ChoiceT1setRef.asn"
 */

#ifndef	_ChoiceT2set_H_
#define	_ChoiceT2set_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetT1.h"
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceT2set_PR {
	ChoiceT2set_PR_NOTHING,	/* No components present */
	ChoiceT2set_PR_one,
	ChoiceT2set_PR_two
} ChoiceT2set_PR;

/* ChoiceT2set */
typedef struct ChoiceT2set {
	ChoiceT2set_PR present;
	union ChoiceT2set_u {
		SetT1_t	 one;
		IA5String_t	 two;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceT2set_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT2set;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT2set_H_ */
#include <asn_internal.h>
