/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetT1+SequenceT2Set+SetT2set+ChoiceT2set+SetOfT2set+SequenceOfT2set+ChoiceT1setRef.asn"
 */

#ifndef	_SetOfT2set_H_
#define	_SetOfT2set_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetT1;

/* SetOfT2set */
typedef struct SetOfT2set {
	A_SET_OF(struct SetT1) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfT2set_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetOfT2set;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetT1.h"

#endif	/* _SetOfT2set_H_ */
#include <asn_internal.h>
