/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetT1+SequenceT2Set+SetT2set+ChoiceT2set+SetOfT2set+SequenceOfT2set+ChoiceT1setRef.asn"
 */

#ifndef	_SetT1setRef_H_
#define	_SetT1setRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetT1setRef */
typedef SetT1_t	 SetT1setRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetT1setRef;
asn_struct_free_f SetT1setRef_free;
asn_struct_print_f SetT1setRef_print;
asn_constr_check_f SetT1setRef_constraint;
ber_type_decoder_f SetT1setRef_decode_ber;
der_type_encoder_f SetT1setRef_encode_der;
xer_type_decoder_f SetT1setRef_decode_xer;
xer_type_encoder_f SetT1setRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SetT1setRef_H_ */
#include <asn_internal.h>
