/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SetT1+SequenceT2Set+SetT2set+ChoiceT2set+SetOfT2set+SequenceOfT2set+ChoiceT1setRef.asn"
 */

#ifndef	_SetT2set_H_
#define	_SetT2set_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetT1.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetT2set_PR {
	SetT2set_PR_one,	/* Member one is present */
	SetT2set_PR_two,	/* Member two is present */
} SetT2set_PR;

/* Forward declarations */
struct SetT1;

/* SetT2set */
typedef struct SetT2set {
	SetT1_t	 one;
	struct SetT1	*two	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetT2set, SetT2set_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetT2set_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetT2set;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetT1.h"

#endif	/* _SetT2set_H_ */
#include <asn_internal.h>
