/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "Choice-SeqWithThisChoice+SeqRecWithThisChoice.asn"
 */

#ifndef	_Choice_SeqWithThisChoice_H_
#define	_Choice_SeqWithThisChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice_SeqWithThisChoice_PR {
	Choice_SeqWithThisChoice_PR_NOTHING,	/* No components present */
	Choice_SeqWithThisChoice_PR_seq
} Choice_SeqWithThisChoice_PR;

/* Forward declarations */
struct SeqRecWithThisChoice;

/* Choice-SeqWithThisChoice */
typedef struct Choice_SeqWithThisChoice {
	Choice_SeqWithThisChoice_PR present;
	union Choice_SeqWithThisChoice_u {
		struct SeqRecWithThisChoice	*seq;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice_SeqWithThisChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice_SeqWithThisChoice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SeqRecWithThisChoice.h"

#endif	/* _Choice_SeqWithThisChoice_H_ */
#include <asn_internal.h>
