/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "Choice-SeqWithThisChoice+SeqRecWithThisChoice.asn"
 */

#ifndef	_SeqRecWithThisChoice_H_
#define	_SeqRecWithThisChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Choice_SeqWithThisChoice;

/* SeqRecWithThisChoice */
typedef struct SeqRecWithThisChoice {
	struct Choice_SeqWithThisChoice	*ch	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqRecWithThisChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqRecWithThisChoice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Choice-SeqWithThisChoice.h"

#endif	/* _SeqRecWithThisChoice_H_ */
#include <asn_internal.h>
