/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#ifndef	_SetRecord_FirstExtension_H_
#define	_SetRecord_FirstExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_FirstExtension_PR {
	SetRecord_FirstExtension_PR_a,	/* Member a is present */
	SetRecord_FirstExtension_PR_b,	/* Member b is present */
	SetRecord_FirstExtension_PR_c,	/* Member c is present */
	SetRecord_FirstExtension_PR_d,	/* Member d is present */
} SetRecord_FirstExtension_PR;

/* SetRecord-FirstExtension */
typedef struct SetRecord_FirstExtension {
	long	 a;
	BOOLEAN_t	*b	/* OPTIONAL */;
	long	*c	/* OPTIONAL */;
	double	 d;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_FirstExtension, SetRecord_FirstExtension_PR_x) */
	unsigned int _presence_map
		[((4+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_FirstExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_FirstExtension;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_FirstExtension_H_ */
#include <asn_internal.h>
