/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#include "SetRecord-FirstExtension.h"

static asn_TYPE_member_t asn_MBR_SetRecord_FirstExtension_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_FirstExtension, a),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"a"
		},
	{ ATF_POINTER, 2, offsetof(struct SetRecord_FirstExtension, b),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"b"
		},
	{ ATF_POINTER, 1, offsetof(struct SetRecord_FirstExtension, c),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"c"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_FirstExtension, d),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"d"
		},
};
static ber_tlv_tag_t asn_DEF_SetRecord_FirstExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SetRecord_FirstExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* b at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* c at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* d at 12 */
};
static uint8_t asn_MAP_SetRecord_FirstExtension_mmap_1[(4 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (1 << 4)
};
static asn_SET_specifics_t asn_SPC_SetRecord_FirstExtension_specs_1 = {
	sizeof(struct SetRecord_FirstExtension),
	offsetof(struct SetRecord_FirstExtension, _asn_ctx),
	offsetof(struct SetRecord_FirstExtension, _presence_map),
	asn_MAP_SetRecord_FirstExtension_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SetRecord_FirstExtension_tag2el_1,	/* Same as above */
	4,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SetRecord_FirstExtension_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SetRecord_FirstExtension = {
	"SetRecord-FirstExtension",
	"SetRecord-FirstExtension",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SetRecord_FirstExtension_tags_1,
	sizeof(asn_DEF_SetRecord_FirstExtension_tags_1)
		/sizeof(asn_DEF_SetRecord_FirstExtension_tags_1[0]), /* 1 */
	asn_DEF_SetRecord_FirstExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetRecord_FirstExtension_tags_1)
		/sizeof(asn_DEF_SetRecord_FirstExtension_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SetRecord_FirstExtension_1,
	4,	/* Elements count */
	&asn_SPC_SetRecord_FirstExtension_specs_1	/* Additional specs */
};

