/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-BS-BSO-BSRef-BSRefO+BitStringRef.asn"
 */

#include "SequenceRecord-BS-BSO-BSRef-BSRefO.h"

static asn_TYPE_member_t asn_MBR_SequenceRecord_BS_BSO_BSRef_BSRefO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_BS_BSO_BSRef_BSRefO, bitString1),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString1"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_BS_BSO_BSRef_BSRefO, bitString2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_BS_BSO_BSRef_BSRefO, bitString3),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BitStringRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString3"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_BS_BSO_BSRef_BSRefO, bitString4),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BitStringRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString4"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_BS_BSO_BSRef_BSRefO_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 2 }, /* bitString1 at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, -1, 1 }, /* bitString3 at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, -2, 0 }, /* bitString4 at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bitString2 at 10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_BS_BSO_BSRef_BSRefO_specs_1 = {
	sizeof(struct SequenceRecord_BS_BSO_BSRef_BSRefO),
	offsetof(struct SequenceRecord_BS_BSO_BSRef_BSRefO, _asn_ctx),
	asn_MAP_SequenceRecord_BS_BSO_BSRef_BSRefO_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO = {
	"SequenceRecord-BS-BSO-BSRef-BSRefO",
	"SequenceRecord-BS-BSO-BSRef-BSRefO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1,
	sizeof(asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_BS_BSO_BSRef_BSRefO_1,
	4,	/* Elements count */
	&asn_SPC_SequenceRecord_BS_BSO_BSRef_BSRefO_specs_1	/* Additional specs */
};

