/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-BS-BSO-BSRef-BSRefO+BitStringRef.asn"
 */

#ifndef	_SequenceRecord_BS_BSO_BSRef_BSRefO_H_
#define	_SequenceRecord_BS_BSO_BSRef_BSRefO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "BitStringRef.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-BS-BSO-BSRef-BSRefO */
typedef struct SequenceRecord_BS_BSO_BSRef_BSRefO {
	BIT_STRING_t	 bitString1;
	BIT_STRING_t	*bitString2	/* OPTIONAL */;
	BitStringRef_t	 bitString3;
	BitStringRef_t	*bitString4	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_BS_BSO_BSRef_BSRefO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_BS_BSO_BSRef_BSRefO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_BS_BSO_BSRef_BSRefO_H_ */
#include <asn_internal.h>
