/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SeqOfT1+SequenceT2seqof+SetT2seqof+ChoiceT2seqof+SetOfT2seqof+SequenceOfT2seqof+ChoiceT1seqofRef.asn"
 */

#ifndef	_ChoiceT2seqof_H_
#define	_ChoiceT2seqof_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SeqOfT1.h"
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceT2seqof_PR {
	ChoiceT2seqof_PR_NOTHING,	/* No components present */
	ChoiceT2seqof_PR_one,
	ChoiceT2seqof_PR_two
} ChoiceT2seqof_PR;

/* ChoiceT2seqof */
typedef struct ChoiceT2seqof {
	ChoiceT2seqof_PR present;
	union ChoiceT2seqof_u {
		SeqOfT1_t	 one;
		IA5String_t	 two;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceT2seqof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT2seqof;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT2seqof_H_ */
#include <asn_internal.h>
