/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest1"
 * 	found in "SeqOfT1+SequenceT2seqof+SetT2seqof+ChoiceT2seqof+SetOfT2seqof+SequenceOfT2seqof+ChoiceT1seqofRef.asn"
 */

#ifndef	_SeqOfT1_H_
#define	_SeqOfT1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SeqOfT1 */
typedef struct SeqOfT1 {
	A_SEQUENCE_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqOfT1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqOfT1;

#ifdef __cplusplus
}
#endif

#endif	/* _SeqOfT1_H_ */
#include <asn_internal.h>
