/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SeqOfT1+SequenceT2seqof+SetT2seqof+ChoiceT2seqof+SetOfT2seqof+SequenceOfT2seqof+ChoiceT1seqofRef.asn"
 */

#ifndef	_SeqOfT1seqofRef_H_
#define	_SeqOfT1seqofRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SeqOfT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SeqOfT1seqofRef */
typedef SeqOfT1_t	 SeqOfT1seqofRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqOfT1seqofRef;
asn_struct_free_f SeqOfT1seqofRef_free;
asn_struct_print_f SeqOfT1seqofRef_print;
asn_constr_check_f SeqOfT1seqofRef_constraint;
ber_type_decoder_f SeqOfT1seqofRef_decode_ber;
der_type_encoder_f SeqOfT1seqofRef_encode_der;
xer_type_decoder_f SeqOfT1seqofRef_decode_xer;
xer_type_encoder_f SeqOfT1seqofRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SeqOfT1seqofRef_H_ */
#include <asn_internal.h>
