/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "SeqOfT1+SequenceT2seqof+SetT2seqof+ChoiceT2seqof+SetOfT2seqof+SequenceOfT2seqof+ChoiceT1seqofRef.asn"
 */

#ifndef	_SetT2seqof_H_
#define	_SetT2seqof_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SeqOfT1.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetT2seqof_PR {
	SetT2seqof_PR_one,	/* Member one is present */
	SetT2seqof_PR_two,	/* Member two is present */
} SetT2seqof_PR;

/* Forward declarations */
struct SeqOfT1;

/* SetT2seqof */
typedef struct SetT2seqof {
	SeqOfT1_t	 one;
	struct SeqOfT1	*two	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetT2seqof, SetT2seqof_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetT2seqof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetT2seqof;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SeqOfT1.h"

#endif	/* _SetT2seqof_H_ */
#include <asn_internal.h>
