/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-SeRef-SeRefO-SeDirRef-SeDirRefO+SetRecord-ISetO-I-IO-I-Ref+SetRecord-ISetO-I-IO-I.asn"
 */

#ifndef	_SetRecord_ISetO_I_IO_I_Ref_H_
#define	_SetRecord_ISetO_I_IO_I_Ref_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetRecord-ISetO-I-IO-I.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetRecord-ISetO-I-IO-I-Ref */
typedef SetRecord_ISetO_I_IO_I_t	 SetRecord_ISetO_I_IO_I_Ref_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_ISetO_I_IO_I_Ref;
asn_struct_free_f SetRecord_ISetO_I_IO_I_Ref_free;
asn_struct_print_f SetRecord_ISetO_I_IO_I_Ref_print;
asn_constr_check_f SetRecord_ISetO_I_IO_I_Ref_constraint;
ber_type_decoder_f SetRecord_ISetO_I_IO_I_Ref_decode_ber;
der_type_encoder_f SetRecord_ISetO_I_IO_I_Ref_encode_der;
xer_type_decoder_f SetRecord_ISetO_I_IO_I_Ref_decode_xer;
xer_type_encoder_f SetRecord_ISetO_I_IO_I_Ref_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_ISetO_I_IO_I_Ref_H_ */
#include <asn_internal.h>
