/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-VSD-VS-VSD-VSD.asn"
 */

#ifndef	_SequenceRecord_VSD_VS_VSD_VSD_H_
#define	_SequenceRecord_VSD_VS_VSD_VSD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-VSD-VS-VSD-VSD */
typedef struct SequenceRecord_VSD_VS_VSD_VSD {
	VisibleString_t	*val1	/* DEFAULT 12"3 */;
	VisibleString_t	 val2;
	VisibleString_t	*val3	/* DEFAULT 567 */;
	VisibleString_t	*val4	/* DEFAULT */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_VSD_VS_VSD_VSD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_VSD_VS_VSD_VSD;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_VSD_VS_VSD_VSD_H_ */
#include <asn_internal.h>
