/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "NullRef.asn"
 */

#ifndef	_NullRef_H_
#define	_NullRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NullRef */
typedef NULL_t	 NullRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NullRef;
asn_struct_free_f NullRef_free;
asn_struct_print_f NullRef_print;
asn_constr_check_f NullRef_constraint;
ber_type_decoder_f NullRef_decode_ber;
der_type_encoder_f NullRef_encode_der;
xer_type_decoder_f NullRef_decode_xer;
xer_type_encoder_f NullRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NullRef_H_ */
#include <asn_internal.h>
