/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-VisS-VisSO-VisSRefWithTag-VisSRefWithTagO+VisibleStringRefWithTag.asn"
 */

#ifndef	_VisibleStringRefWithTag_H_
#define	_VisibleStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VisibleStringRefWithTag */
typedef VisibleString_t	 VisibleStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VisibleStringRefWithTag;
asn_struct_free_f VisibleStringRefWithTag_free;
asn_struct_print_f VisibleStringRefWithTag_print;
asn_constr_check_f VisibleStringRefWithTag_constraint;
ber_type_decoder_f VisibleStringRefWithTag_decode_ber;
der_type_encoder_f VisibleStringRefWithTag_encode_der;
xer_type_decoder_f VisibleStringRefWithTag_decode_xer;
xer_type_encoder_f VisibleStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VisibleStringRefWithTag_H_ */
#include <asn_internal.h>
