/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-TeleS-TeleSO-TeleSRefWithTag-TeleSRefWithTagO+TeletexStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO_H_
#define	_SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>
#include "TeletexStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-TeleS-TeleSO-TeleSRefWithTag-TeleSRefWithTagO */
typedef struct SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO {
	struct seq {
		TeletexString_t	 str1;
		TeletexString_t	*str2	/* OPTIONAL */;
		TeletexStringRefWithTag_t	 str3;
		TeletexStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_TeleS_TeleSO_TeleSRefWithTag_TeleSRefWithTagO_H_ */
#include <asn_internal.h>
