/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-TeleS-TeleSO-TeleSRefWithTag-TeleSRefWithTagO+TeletexStringRefWithTag.asn"
 */

#ifndef	_TeletexStringRefWithTag_H_
#define	_TeletexStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TeletexStringRefWithTag */
typedef TeletexString_t	 TeletexStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TeletexStringRefWithTag;
asn_struct_free_f TeletexStringRefWithTag_free;
asn_struct_print_f TeletexStringRefWithTag_print;
asn_constr_check_f TeletexStringRefWithTag_constraint;
ber_type_decoder_f TeletexStringRefWithTag_decode_ber;
der_type_encoder_f TeletexStringRefWithTag_encode_der;
xer_type_decoder_f TeletexStringRefWithTag_decode_xer;
xer_type_encoder_f TeletexStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TeletexStringRefWithTag_H_ */
#include <asn_internal.h>
