/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-B-BO.asn"
 */

#include "SequenceRecord-B-BO.h"

static asn_TYPE_member_t asn_MBR_SequenceRecord_B_BO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_B_BO, bool1),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bool1"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_B_BO, bool2),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bool2"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_B_BO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_B_BO_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 1 }, /* bool1 at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, -1, 0 } /* bool2 at 10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_B_BO_specs_1 = {
	sizeof(struct SequenceRecord_B_BO),
	offsetof(struct SequenceRecord_B_BO, _asn_ctx),
	asn_MAP_SequenceRecord_B_BO_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_B_BO = {
	"SequenceRecord-B-BO",
	"SequenceRecord-B-BO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_B_BO_tags_1,
	sizeof(asn_DEF_SequenceRecord_B_BO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_B_BO_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_B_BO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_B_BO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_B_BO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_B_BO_1,
	2,	/* Elements count */
	&asn_SPC_SequenceRecord_B_BO_specs_1	/* Additional specs */
};

