
SOME-MODULE

DEFINITIONS IMPLICIT TAGS    ::=

BEGIN

SequenceRecord-B-BO ::= SEQUENCE {
	bool1 BOOLEAN,
	continue BOOLEAN OPTIONAL --it is also a test of reserved keywords replacement
}

END
