/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-T61S-T61SO-T61SRefWithTag-T61SRefWithTagO+T61StringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO_H_
#define	_SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <T61String.h>
#include "T61StringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-T61S-T61SO-T61SRefWithTag-T61SRefWithTagO */
typedef struct SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO {
	struct seq {
		T61String_t	 str1;
		T61String_t	*str2	/* OPTIONAL */;
		T61StringRefWithTag_t	 str3;
		T61StringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_T61S_T61SO_T61SRefWithTag_T61SRefWithTagO_H_ */
#include <asn_internal.h>
