/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-T61S-T61SO-T61SRefWithTag-T61SRefWithTagO+T61StringRefWithTag.asn"
 */

#ifndef	_T61StringRefWithTag_H_
#define	_T61StringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <T61String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T61StringRefWithTag */
typedef T61String_t	 T61StringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T61StringRefWithTag;
asn_struct_free_f T61StringRefWithTag_free;
asn_struct_print_f T61StringRefWithTag_print;
asn_constr_check_f T61StringRefWithTag_constraint;
ber_type_decoder_f T61StringRefWithTag_decode_ber;
der_type_encoder_f T61StringRefWithTag_encode_der;
xer_type_decoder_f T61StringRefWithTag_decode_xer;
xer_type_encoder_f T61StringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _T61StringRefWithTag_H_ */
#include <asn_internal.h>
