/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-BD-B-BD.asn"
 */

#ifndef	_SequenceRecord_BD_B_BD_H_
#define	_SequenceRecord_BD_B_BD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-BD-B-BD */
typedef struct SequenceRecord_BD_B_BD {
	BOOLEAN_t	*val1	/* DEFAULT TRUE */;
	BOOLEAN_t	 val2;
	BOOLEAN_t	*val3	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_BD_B_BD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_BD_B_BD;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_BD_B_BD_H_ */
#include <asn_internal.h>
