/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-BD-B-BD.asn"
 */

#include "SequenceRecord-BD-B-BD.h"

static asn_TYPE_member_t asn_MBR_SequenceRecord_BD_B_BD_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_BD_B_BD, val1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"val1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_BD_B_BD, val2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"val2"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_BD_B_BD, val3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"val3"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_BD_B_BD_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_BD_B_BD_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* val1 at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* val2 at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* val3 at 11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_BD_B_BD_specs_1 = {
	sizeof(struct SequenceRecord_BD_B_BD),
	offsetof(struct SequenceRecord_BD_B_BD, _asn_ctx),
	asn_MAP_SequenceRecord_BD_B_BD_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_BD_B_BD = {
	"SequenceRecord-BD-B-BD",
	"SequenceRecord-BD-B-BD",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_BD_B_BD_tags_1,
	sizeof(asn_DEF_SequenceRecord_BD_B_BD_tags_1)
		/sizeof(asn_DEF_SequenceRecord_BD_B_BD_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_BD_B_BD_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_BD_B_BD_tags_1)
		/sizeof(asn_DEF_SequenceRecord_BD_B_BD_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_BD_B_BD_1,
	3,	/* Elements count */
	&asn_SPC_SequenceRecord_BD_B_BD_specs_1	/* Additional specs */
};

