/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "EnumeratedTest.asn"
 */

#ifndef	_EnumeratedTest_H_
#define	_EnumeratedTest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnumeratedTest {
	EnumeratedTest_variant1	= 1,
	EnumeratedTest_variant2	= 2,
	EnumeratedTest_variant3	= 3,
	EnumeratedTest_variant10	= 10
} e_EnumeratedTest;

/* EnumeratedTest */
typedef long	 EnumeratedTest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumeratedTest;
asn_struct_free_f EnumeratedTest_free;
asn_struct_print_f EnumeratedTest_print;
asn_constr_check_f EnumeratedTest_constraint;
ber_type_decoder_f EnumeratedTest_decode_ber;
der_type_encoder_f EnumeratedTest_encode_der;
xer_type_decoder_f EnumeratedTest_decode_xer;
xer_type_encoder_f EnumeratedTest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumeratedTest_H_ */
#include <asn_internal.h>
