/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-DirectRef+DirectRefRecord-S-I-IO-IO+SequenceRecord-I-IO-I-IMPLICIT.asn"
 */

#ifndef	_SequenceRecord_I_IO_I_Auto_H_
#define	_SequenceRecord_I_IO_I_Auto_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-I-IO-I-Auto */
typedef struct SequenceRecord_I_IO_I_Auto {
	long	 type;
	long	*type2	/* OPTIONAL */;
	long	 type3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_I_IO_I_Auto_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_I_IO_I_Auto;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_I_IO_I_Auto_H_ */
#include <asn_internal.h>
