/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-UTF8S-UTF8SO-UTF8SRefWithTag-UTF8SRefWithTagO+UTF8StringRefWithTag.asn"
 */

#ifndef	_UTF8StringRefWithTag_H_
#define	_UTF8StringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UTF8StringRefWithTag */
typedef UTF8String_t	 UTF8StringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UTF8StringRefWithTag;
asn_struct_free_f UTF8StringRefWithTag_free;
asn_struct_print_f UTF8StringRefWithTag_print;
asn_constr_check_f UTF8StringRefWithTag_constraint;
ber_type_decoder_f UTF8StringRefWithTag_decode_ber;
der_type_encoder_f UTF8StringRefWithTag_encode_der;
xer_type_decoder_f UTF8StringRefWithTag_decode_xer;
xer_type_encoder_f UTF8StringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UTF8StringRefWithTag_H_ */
#include <asn_internal.h>
