
SOME-MODULE

DEFINITIONS IMPLICIT TAGS    ::=

BEGIN

SequenceRecord-IS-C-R-I-B ::= SEQUENCE {
	set SEQUENCE {
		choice CHOICE {
			real REAL,
			integer INTEGER
		},
		boolean BOOLEAN
	}
} 

END
