/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "Simplified.asn"
 */

#ifndef	_SequenceRecord_I_IO_IRef_H_
#define	_SequenceRecord_I_IO_IRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SequenceRecord-I-IO-I.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-I-IO-IRef */
typedef SequenceRecord_I_IO_I_t	 SequenceRecord_I_IO_IRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_I_IO_IRef;
asn_struct_free_f SequenceRecord_I_IO_IRef_free;
asn_struct_print_f SequenceRecord_I_IO_IRef_print;
asn_constr_check_f SequenceRecord_I_IO_IRef_constraint;
ber_type_decoder_f SequenceRecord_I_IO_IRef_decode_ber;
der_type_encoder_f SequenceRecord_I_IO_IRef_encode_der;
xer_type_decoder_f SequenceRecord_I_IO_IRef_decode_xer;
xer_type_encoder_f SequenceRecord_I_IO_IRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_I_IO_IRef_H_ */
#include <asn_internal.h>
