/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-OI-OIO-OIRef-OIRefO+ObjectIdentifierRef.asn"
 */

#ifndef	_ObjectIdentifierRef_H_
#define	_ObjectIdentifierRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectIdentifierRef */
typedef OBJECT_IDENTIFIER_t	 ObjectIdentifierRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectIdentifierRef;
asn_struct_free_f ObjectIdentifierRef_free;
asn_struct_print_f ObjectIdentifierRef_print;
asn_constr_check_f ObjectIdentifierRef_constraint;
ber_type_decoder_f ObjectIdentifierRef_decode_ber;
der_type_encoder_f ObjectIdentifierRef_encode_der;
xer_type_decoder_f ObjectIdentifierRef_decode_xer;
xer_type_encoder_f ObjectIdentifierRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectIdentifierRef_H_ */
#include <asn_internal.h>
