/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-OI-OIO-OIRef-OIRefO+ObjectIdentifierRef.asn"
 */

#ifndef	_SequenceRecord_IS_OI_OIO_OIRef_OIRefO_H_
#define	_SequenceRecord_IS_OI_OIO_OIRef_OIRefO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "ObjectIdentifierRef.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-OI-OIO-OIRef-OIRefO */
typedef struct SequenceRecord_IS_OI_OIO_OIRef_OIRefO {
	struct seq {
		OBJECT_IDENTIFIER_t	 objectIdentifier1;
		OBJECT_IDENTIFIER_t	*objectIdentifier2	/* OPTIONAL */;
		ObjectIdentifierRef_t	 objectIdentifier3;
		ObjectIdentifierRef_t	*objectIdentifier4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_OI_OIO_OIRef_OIRefO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_OI_OIO_OIRef_OIRefO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_OI_OIO_OIRef_OIRefO_H_ */
#include <asn_internal.h>
