/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-BmpS-BmpSO-BmpSRefWithTag-BmpSRefWithTagO+BMPStringRefWithTag.asn"
 */

#ifndef	_BMPStringRefWithTag_H_
#define	_BMPStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BMPString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BMPStringRefWithTag */
typedef BMPString_t	 BMPStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BMPStringRefWithTag;
asn_struct_free_f BMPStringRefWithTag_free;
asn_struct_print_f BMPStringRefWithTag_print;
asn_constr_check_f BMPStringRefWithTag_constraint;
ber_type_decoder_f BMPStringRefWithTag_decode_ber;
der_type_encoder_f BMPStringRefWithTag_encode_der;
xer_type_decoder_f BMPStringRefWithTag_decode_xer;
xer_type_encoder_f BMPStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _BMPStringRefWithTag_H_ */
#include <asn_internal.h>
