/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-BmpS-BmpSO-BmpSRefWithTag-BmpSRefWithTagO+BMPStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO_H_
#define	_SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BMPString.h>
#include "BMPStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-BmpS-BmpSO-BmpSRefWithTag-BmpSRefWithTagO */
typedef struct SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO {
	struct seq {
		BMPString_t	 str1;
		BMPString_t	*str2	/* OPTIONAL */;
		BMPStringRefWithTag_t	 str3;
		BMPStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_BmpS_BmpSO_BmpSRefWithTag_BmpSRefWithTagO_H_ */
#include <asn_internal.h>
