/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "UnsignedNativeIntegerTest.asn"
 */

#ifndef	_UnsignedNativeIntegerTest_H_
#define	_UnsignedNativeIntegerTest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnsignedNativeIntegerTest */
typedef unsigned long	 UnsignedNativeIntegerTest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsignedNativeIntegerTest;
asn_struct_free_f UnsignedNativeIntegerTest_free;
asn_struct_print_f UnsignedNativeIntegerTest_print;
asn_constr_check_f UnsignedNativeIntegerTest_constraint;
ber_type_decoder_f UnsignedNativeIntegerTest_decode_ber;
der_type_encoder_f UnsignedNativeIntegerTest_encode_der;
xer_type_decoder_f UnsignedNativeIntegerTest_decode_xer;
xer_type_encoder_f UnsignedNativeIntegerTest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnsignedNativeIntegerTest_H_ */
#include <asn_internal.h>
