/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "EnumeratedRefRef+EnumeratedRef.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_EnumeratedRef_H_
#define	_EnumeratedRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
//typedef enum EnumeratedRef {
//} e_EnumeratedRef;

/* EnumeratedRef */
typedef long	 EnumeratedRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumeratedRef;
asn_struct_free_f EnumeratedRef_free;
asn_struct_print_f EnumeratedRef_print;
asn_constr_check_f EnumeratedRef_constraint;
ber_type_decoder_f EnumeratedRef_decode_ber;
der_type_encoder_f EnumeratedRef_encode_der;
xer_type_decoder_f EnumeratedRef_decode_xer;
xer_type_encoder_f EnumeratedRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumeratedRef_H_ */
#include <asn_internal.h>
