/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "EnumeratedRefRef+EnumeratedRef.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_EnumeratedRefRef_H_
#define	_EnumeratedRefRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EnumeratedRef.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EnumeratedRefRef */
typedef EnumeratedRef_t	 EnumeratedRefRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumeratedRefRef;
asn_struct_free_f EnumeratedRefRef_free;
asn_struct_print_f EnumeratedRefRef_print;
asn_constr_check_f EnumeratedRefRef_constraint;
ber_type_decoder_f EnumeratedRefRef_decode_ber;
der_type_encoder_f EnumeratedRefRef_encode_der;
xer_type_decoder_f EnumeratedRefRef_decode_xer;
xer_type_encoder_f EnumeratedRefRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumeratedRefRef_H_ */
#include <asn_internal.h>
