
SOME-MODULE

DEFINITIONS IMPLICIT TAGS    ::=

BEGIN

SetRecord-ISet-CO-R-I-B ::= SET {
	set SET {
		choice CHOICE {
			real REAL,
			integer INTEGER
		} OPTIONAL,
		boolean BOOLEAN
	}
} 

END
