/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-ISet-CO-R-I-B.asn"
 */

#ifndef	_SetRecord_ISet_CO_R_I_B_H_
#define	_SetRecord_ISet_CO_R_I_B_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_ISet_CO_R_I_B_PR {
	SetRecord_ISet_CO_R_I_B_PR_set,	/* Member set is present */
} SetRecord_ISet_CO_R_I_B_PR;

/*
 * Method of determining the components presence
 */
typedef enum set_PR {
	set_PR_choice,	/* Member choice is present */
	set_PR_boolean,	/* Member boolean is present */
} set_PR;
typedef enum choice_PR {
	choice_PR_NOTHING,	/* No components present */
	choice_PR_real,
	choice_PR_integer
} choice_PR;

/* SetRecord-ISet-CO-R-I-B */
typedef struct SetRecord_ISet_CO_R_I_B {
	struct set {
		struct choice {
			choice_PR present;
			union SetRecord_ISet_CO_R_I_B__set__choice_u {
				double	 real;
				long	 integer;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *choice;
		BOOLEAN_t	 boolean;
		
		/* Presence bitmask: ASN_SET_ISPRESENT(pset, set_PR_x) */
		unsigned int _presence_map
			[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} set;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_ISet_CO_R_I_B, SetRecord_ISet_CO_R_I_B_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_ISet_CO_R_I_B_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_ISet_CO_R_I_B;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_ISet_CO_R_I_B_H_ */
#include <asn_internal.h>
