/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "Choice-IChoiceRealInteger.asn"
 */

#ifndef	_Choice_IChoiceRealInteger_H_
#define	_Choice_IChoiceRealInteger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice_IChoiceRealInteger_PR {
	Choice_IChoiceRealInteger_PR_NOTHING,	/* No components present */
	Choice_IChoiceRealInteger_PR_choice
} Choice_IChoiceRealInteger_PR;
typedef enum choice_PR {
	choice_PR_NOTHING,	/* No components present */
	choice_PR_real,
	choice_PR_integer
} choice_PR;

/* Choice-IChoiceRealInteger */
typedef struct Choice_IChoiceRealInteger {
	Choice_IChoiceRealInteger_PR present;
	union Choice_IChoiceRealInteger_u {
		struct choice {
			choice_PR present;
			union Choice_IChoiceRealInteger__choice_u {
				double	 real;
				long	 integer;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} choice;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice_IChoiceRealInteger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice_IChoiceRealInteger;

#ifdef __cplusplus
}
#endif

#endif	/* _Choice_IChoiceRealInteger_H_ */
#include <asn_internal.h>
