/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetOfEnumerated.asn"
 */

#ifndef	_SetOfEnumerated_H_
#define	_SetOfEnumerated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Member {
	Member_value1	= 1,
	Member_value2	= 2,
	Member_value3	= 3
} e_Member;

/* SetOfEnumerated */
typedef struct SetOfEnumerated {
	A_SET_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetOfEnumerated_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Member_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SetOfEnumerated;

#ifdef __cplusplus
}
#endif

#endif	/* _SetOfEnumerated_H_ */
#include <asn_internal.h>
