/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 * 	`asn1c -fnative-types`
 */

#ifndef	_SetRecord_empty_H_
#define	_SetRecord_empty_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_empty_PR {
	SetRecord_empty_PR_int,	/* Member int is present */
	SetRecord_empty_PR_real,	/* Member real is present */
} SetRecord_empty_PR;

/* SetRecord-empty */
typedef struct SetRecord_empty {
	long	 Int;
	double	 real;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_empty, SetRecord_empty_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_empty_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_empty;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_empty_H_ */
#include <asn_internal.h>
