/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 * 	`asn1c -fnative-types`
 */

#include "SetRecord-empty.h"

static asn_TYPE_member_t asn_MBR_SetRecord_empty_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_empty, Int),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"int"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetRecord_empty, real),
		(ASN_TAG_CLASS_UNIVERSAL | (9 << 2)),
		0,
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"real"
		},
};
static ber_tlv_tag_t asn_DEF_SetRecord_empty_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SetRecord_empty_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* int at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (9 << 2)), 1, 0, 0 } /* real at 10 */
};
static uint8_t asn_MAP_SetRecord_empty_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6)
};
static asn_SET_specifics_t asn_SPC_SetRecord_empty_specs_1 = {
	sizeof(struct SetRecord_empty),
	offsetof(struct SetRecord_empty, _asn_ctx),
	offsetof(struct SetRecord_empty, _presence_map),
	asn_MAP_SetRecord_empty_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_SetRecord_empty_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SetRecord_empty_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SetRecord_empty = {
	"SetRecord-empty",
	"SetRecord-empty",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SetRecord_empty_tags_1,
	sizeof(asn_DEF_SetRecord_empty_tags_1)
		/sizeof(asn_DEF_SetRecord_empty_tags_1[0]), /* 1 */
	asn_DEF_SetRecord_empty_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetRecord_empty_tags_1)
		/sizeof(asn_DEF_SetRecord_empty_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SetRecord_empty_1,
	2,	/* Elements count */
	&asn_SPC_SetRecord_empty_specs_1	/* Additional specs */
};

