/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-DirectRef-EXPL+DirectRefRecord-S-I-IO-I-EXPL+SequenceRecord-I-IO-I-EXPL.asn"
 */

#ifndef	_SequenceRecord_DirectRef_EXPL_H_
#define	_SequenceRecord_DirectRef_EXPL_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DirectRefRecord-S-I-IO-I-EXPL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-DirectRef-EXPL */
typedef struct SequenceRecord_DirectRef_EXPL {
	DirectRefRecord_S_I_IO_I_EXPL_t	 field;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_DirectRef_EXPL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_DirectRef_EXPL;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_DirectRef_EXPL_H_ */
#include <asn_internal.h>
