/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-ISet-Sets-of-enumerated.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_SetRecord_ISet_Sets_of_enumerated_H_
#define	_SetRecord_ISet_Sets_of_enumerated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_ISet_Sets_of_enumerated_PR {
	SetRecord_ISet_Sets_of_enumerated_PR_set,	/* Member set is present */
} SetRecord_ISet_Sets_of_enumerated_PR;

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_ISet_Sets_of_enumerated__set_PR {
	SetRecord_ISet_Sets_of_enumerated__set_PR_field3,	/* Member field3 is present */
	SetRecord_ISet_Sets_of_enumerated__set_PR_field4,	/* Member field4 is present */
} SetRecord_ISet_Sets_of_enumerated__set_PR;
typedef enum SetRecord_ISet_Sets_of_enumerated__set__field3__Member {
	SetRecord_ISet_Sets_of_enumerated__set__field3__Member_value1	= 1,
	SetRecord_ISet_Sets_of_enumerated__set__field3__Member_value2	= 2,
	SetRecord_ISet_Sets_of_enumerated__set__field3__Member_value3	= 3
} e_SetRecord_ISet_Sets_of_enumerated__set__field3__Member;
typedef enum SetRecord_ISet_Sets_of_enumerated__set__field4__Member {
	SetRecord_ISet_Sets_of_enumerated__set__field4__Member_value1	= 1,
	SetRecord_ISet_Sets_of_enumerated__set__field4__Member_value2	= 2,
	SetRecord_ISet_Sets_of_enumerated__set__field4__Member_value3	= 3
} e_SetRecord_ISet_Sets_of_enumerated__set__field4__Member;

/* SetRecord-ISet-Sets-of-enumerated */
typedef struct SetRecord_ISet_Sets_of_enumerated {
	struct SetRecord_ISet_Sets_of_enumerated__set {
		struct SetRecord_ISet_Sets_of_enumerated__set__field3 {
			A_SET_OF(long) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} field3;
		struct SetRecord_ISet_Sets_of_enumerated__set__field4 {
			A_SET_OF(long) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *field4;
		
		/* Presence bitmask: ASN_SET_ISPRESENT(pset, set_PR_x) */
		unsigned int _presence_map
			[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} set;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_ISet_Sets_of_enumerated, SetRecord_ISet_Sets_of_enumerated_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_ISet_Sets_of_enumerated_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Member_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Member_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_ISet_Sets_of_enumerated;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRecord_ISet_Sets_of_enumerated_H_ */
#include <asn_internal.h>
