/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-GraS-GraSO-GraSRefWithTag-GraSRefWithTagO+GraStringRefWithTag.asn"
 */

#ifndef	_GraStringRefWithTag_H_
#define	_GraStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GraStringRefWithTag */
typedef GraphicString_t	 GraStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GraStringRefWithTag;
asn_struct_free_f GraStringRefWithTag_free;
asn_struct_print_f GraStringRefWithTag_print;
asn_constr_check_f GraStringRefWithTag_constraint;
ber_type_decoder_f GraStringRefWithTag_decode_ber;
der_type_encoder_f GraStringRefWithTag_encode_der;
xer_type_decoder_f GraStringRefWithTag_decode_xer;
xer_type_encoder_f GraStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GraStringRefWithTag_H_ */
#include <asn_internal.h>
