/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-GraS-GraSO-GraSRefWithTag-GraSRefWithTagO+GraStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO_H_
#define	_SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>
#include "GraStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-GraS-GraSO-GraSRefWithTag-GraSRefWithTagO */
typedef struct SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO {
	struct seq {
		GraphicString_t	 str1;
		GraphicString_t	*str2	/* OPTIONAL */;
		GraStringRefWithTag_t	 str3;
		GraStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_GraS_GraSO_GraSRefWithTag_GraSRefWithTagO_H_ */
#include <asn_internal.h>
