/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-PriS-PriSO-PriSRefWithTag-PriSRefWithTagO+PrintableStringRefWithTag.asn"
 */

#ifndef	_PrintableStringRefWithTag_H_
#define	_PrintableStringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrintableStringRefWithTag */
typedef PrintableString_t	 PrintableStringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrintableStringRefWithTag;
asn_struct_free_f PrintableStringRefWithTag_free;
asn_struct_print_f PrintableStringRefWithTag_print;
asn_constr_check_f PrintableStringRefWithTag_constraint;
ber_type_decoder_f PrintableStringRefWithTag_decode_ber;
der_type_encoder_f PrintableStringRefWithTag_encode_der;
xer_type_decoder_f PrintableStringRefWithTag_decode_xer;
xer_type_encoder_f PrintableStringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PrintableStringRefWithTag_H_ */
#include <asn_internal.h>
