/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-PriS-PriSO-PriSRefWithTag-PriSRefWithTagO+PrintableStringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO_H_
#define	_SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include "PrintableStringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-PriS-PriSO-PriSRefWithTag-PriSRefWithTagO */
typedef struct SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO {
	struct seq {
		PrintableString_t	 str1;
		PrintableString_t	*str2	/* OPTIONAL */;
		PrintableStringRefWithTag_t	 str3;
		PrintableStringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_PriS_PriSO_PriSRefWithTag_PriSRefWithTagO_H_ */
#include <asn_internal.h>
