/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-PSD-PS-PSD-PSD.asn"
 */

#ifndef	_SequenceRecord_PSD_PS_PSD_PSD_H_
#define	_SequenceRecord_PSD_PS_PSD_PSD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-PSD-PS-PSD-PSD */
typedef struct SequenceRecord_PSD_PS_PSD_PSD {
	PrintableString_t	*val1	/* DEFAULT 12"3 */;
	PrintableString_t	 val2;
	PrintableString_t	*val3	/* DEFAULT 567 */;
	PrintableString_t	*val4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_PSD_PS_PSD_PSD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_PSD_PS_PSD_PSD;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_PSD_PS_PSD_PSD_H_ */
#include <asn_internal.h>
