/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SetRecord-ESet-2+SetRecord-ESetO-2.asn"
 */

#ifndef	_SetRecord_ESetO_2_H_
#define	_SetRecord_ESetO_2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SetRecord_ESetO_2_PR {
	SetRecord_ESetO_2_PR_ptr2,	/* Member ptr2 is present */
} SetRecord_ESetO_2_PR;

/* Forward declarations */
struct SetRecord_ESet_2;

/* SetRecord-ESetO-2 */
typedef struct SetRecord_ESetO_2 {
	struct SetRecord_ESet_2	*ptr2	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSetRecord_ESetO_2, SetRecord_ESetO_2_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRecord_ESetO_2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRecord_ESetO_2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetRecord-ESet-2.h"

#endif	/* _SetRecord_ESetO_2_H_ */
#include <asn_internal.h>
