
SOME-MODULE

DEFINITIONS IMPLICIT TAGS    ::=

BEGIN

SetRecord-ESet-2    ::= SET {
	ptr1 [10] SetRecord-ESetO-2
}

SetRecord-ESetO-2 ::= SET {
	ptr2 SetRecord-ESet-2 OPTIONAL
}
 

END
