/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "IntegerRefWithTag.asn"
 */

#ifndef	_IntegerRefWithTag_H_
#define	_IntegerRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntegerRefWithTag */
typedef long	 IntegerRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntegerRefWithTag;
asn_struct_free_f IntegerRefWithTag_free;
asn_struct_print_f IntegerRefWithTag_print;
asn_constr_check_f IntegerRefWithTag_constraint;
ber_type_decoder_f IntegerRefWithTag_decode_ber;
der_type_encoder_f IntegerRefWithTag_encode_der;
xer_type_decoder_f IntegerRefWithTag_decode_xer;
xer_type_encoder_f IntegerRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IntegerRefWithTag_H_ */
#include <asn_internal.h>
