/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ID-I-ID-ID.asn"
 */

#include "SequenceRecord-ID-I-ID-ID.h"

static int asn_DFL_2_set_123(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 123 */
		*st = 123;
		return 0;
	} else {
		/* Test default value 123 */
		return (*st == 123);
	}
}
static int asn_DFL_4_set_0(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static int asn_DFL_5_set_567(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 567 */
		*st = 567;
		return 0;
	} else {
		/* Test default value 567 */
		return (*st == 567);
	}
}
static asn_TYPE_member_t asn_MBR_SequenceRecord_ID_I_ID_ID_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_ID_I_ID_ID, val1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_123,	/* DEFAULT 123 */
		"val1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_ID_I_ID_ID, val2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"val2"
		},
	{ ATF_NOFLAGS, 2, offsetof(struct SequenceRecord_ID_I_ID_ID, val3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_4_set_0,	/* DEFAULT 0 */
		"val3"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_ID_I_ID_ID, val4),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_5_set_567,	/* DEFAULT 567 */
		"val4"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_ID_I_ID_ID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* val1 at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* val2 at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* val3 at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* val4 at 12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_ID_I_ID_ID_specs_1 = {
	sizeof(struct SequenceRecord_ID_I_ID_ID),
	offsetof(struct SequenceRecord_ID_I_ID_ID, _asn_ctx),
	asn_MAP_SequenceRecord_ID_I_ID_ID_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ID_I_ID_ID = {
	"SequenceRecord-ID-I-ID-ID",
	"SequenceRecord-ID-I-ID-ID",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1,
	sizeof(asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1)
		/sizeof(asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1)
		/sizeof(asn_DEF_SequenceRecord_ID_I_ID_ID_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_ID_I_ID_ID_1,
	4,	/* Elements count */
	&asn_SPC_SequenceRecord_ID_I_ID_ID_specs_1	/* Additional specs */
};

