/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ID-I-ID-ID.asn"
 */

#ifndef	_SequenceRecord_ID_I_ID_ID_H_
#define	_SequenceRecord_ID_I_ID_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-ID-I-ID-ID */
typedef struct SequenceRecord_ID_I_ID_ID {
	long	*val1	/* DEFAULT 123 */;
	long	 val2;
	long	 val3	/* DEFAULT 0 */;
	long	*val4	/* DEFAULT 567 */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ID_I_ID_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ID_I_ID_ID;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_ID_I_ID_ID_H_ */
#include <asn_internal.h>
