/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ESO+SequenceRecord-IO.asn"
 */

#ifndef	_SequenceRecord_ESO_H_
#define	_SequenceRecord_ESO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceRecord_IO;

/* SequenceRecord-ESO */
typedef struct SequenceRecord_ESO {
	struct SequenceRecord_IO	*type	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ESO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ESO;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SequenceRecord-IO.h"

#endif	/* _SequenceRecord_ESO_H_ */
#include <asn_internal.h>
