/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-GT-GTO-GTRefWithTag-GTRefWithTagO+GeneralizedTimeRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO_H_
#define	_SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralizedTime.h>
#include "GeneralizedTimeRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-GT-GTO-GTRefWithTag-GTRefWithTagO */
typedef struct SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO {
	struct seq {
		GeneralizedTime_t	 time1;
		GeneralizedTime_t	*time2	/* OPTIONAL */;
		GeneralizedTimeRefWithTag_t	 time3;
		GeneralizedTimeRefWithTag_t	*time4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_GT_GTO_GTRefWithTag_GTRefWithTagO_H_ */
#include <asn_internal.h>
