/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-N-NO.asn"
 */

#ifndef	_SequenceRecord_N_NO_H_
#define	_SequenceRecord_N_NO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-N-NO */
typedef struct SequenceRecord_N_NO {
	NULL_t	 null1;
	NULL_t	*null2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_N_NO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_N_NO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_N_NO_H_ */
#include <asn_internal.h>
