/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO+IA5StringRefWithTag.asn"
 */

#ifndef	_IA5StringRefWithTag_H_
#define	_IA5StringRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IA5StringRefWithTag */
typedef IA5String_t	 IA5StringRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IA5StringRefWithTag;
asn_struct_free_f IA5StringRefWithTag_free;
asn_struct_print_f IA5StringRefWithTag_print;
asn_constr_check_f IA5StringRefWithTag_constraint;
ber_type_decoder_f IA5StringRefWithTag_decode_ber;
der_type_encoder_f IA5StringRefWithTag_encode_der;
xer_type_decoder_f IA5StringRefWithTag_decode_xer;
xer_type_encoder_f IA5StringRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IA5StringRefWithTag_H_ */
#include <asn_internal.h>
