/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO+IA5StringRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_H_
#define	_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include "IA5StringRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO */
typedef struct SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO {
	struct seq {
		IA5String_t	 str1;
		IA5String_t	*str2	/* OPTIONAL */;
		IA5StringRefWithTag_t	 str3;
		IA5StringRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_H_ */
#include <asn_internal.h>
