/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO+IA5StringRefWithTag.asn"
 */

#include "SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO.h"

static asn_TYPE_member_t asn_MBR_seq_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct seq, str1),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"str1"
		},
	{ ATF_POINTER, 1, offsetof(struct seq, str2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"str2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct seq, str3),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		0,
		&asn_DEF_IA5StringRefWithTag,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"str3"
		},
	{ ATF_POINTER, 1, offsetof(struct seq, str4),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		0,
		&asn_DEF_IA5StringRefWithTag,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"str4"
		},
};
static ber_tlv_tag_t asn_DEF_seq_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_seq_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 }, /* str1 at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* str2 at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 2, 0, 1 }, /* str3 at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 3, -1, 0 } /* str4 at 13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_seq_specs_2 = {
	sizeof(struct seq),
	offsetof(struct seq, _asn_ctx),
	asn_MAP_seq_tag2el_2,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_seq_2 = {
	"seq",
	"seq",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_seq_tags_2,
	sizeof(asn_DEF_seq_tags_2)
		/sizeof(asn_DEF_seq_tags_2[0]), /* 1 */
	asn_DEF_seq_tags_2,	/* Same as above */
	sizeof(asn_DEF_seq_tags_2)
		/sizeof(asn_DEF_seq_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_seq_2,
	4,	/* Elements count */
	&asn_SPC_seq_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO, seq),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_seq_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"seq"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* seq at 10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_specs_1 = {
	sizeof(struct SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO),
	offsetof(struct SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO, _asn_ctx),
	asn_MAP_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO = {
	"SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO",
	"SequenceRecord-IS-IA5S-IA5SO-IA5SRefWithTag-IA5SRefWithTagO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1,
	sizeof(asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1)
		/sizeof(asn_DEF_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_1,
	1,	/* Elements count */
	&asn_SPC_SequenceRecord_IS_IA5S_IA5SO_IA5SRefWithTag_IA5SRefWithTagO_specs_1	/* Additional specs */
};

