/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-ObjD-ObjDO-ObjDRefWithTag-ObjDRefWithTagO+ObjDescRefWithTag.asn"
 */

#ifndef	_ObjDescRefWithTag_H_
#define	_ObjDescRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ObjectDescriptor.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObjDescRefWithTag */
typedef ObjectDescriptor_t	 ObjDescRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjDescRefWithTag;
asn_struct_free_f ObjDescRefWithTag_free;
asn_struct_print_f ObjDescRefWithTag_print;
asn_constr_check_f ObjDescRefWithTag_constraint;
ber_type_decoder_f ObjDescRefWithTag_decode_ber;
der_type_encoder_f ObjDescRefWithTag_encode_der;
xer_type_decoder_f ObjDescRefWithTag_decode_xer;
xer_type_encoder_f ObjDescRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjDescRefWithTag_H_ */
#include <asn_internal.h>
