/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-ObjD-ObjDO-ObjDRefWithTag-ObjDRefWithTagO+ObjDescRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO_H_
#define	_SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ObjectDescriptor.h>
#include "ObjDescRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-ObjD-ObjDO-ObjDRefWithTag-ObjDRefWithTagO */
typedef struct SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO {
	struct seq {
		ObjectDescriptor_t	 str1;
		ObjectDescriptor_t	*str2	/* OPTIONAL */;
		ObjDescRefWithTag_t	 str3;
		ObjDescRefWithTag_t	*str4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_ObjD_ObjDO_ObjDRefWithTag_ObjDRefWithTagO_H_ */
#include <asn_internal.h>
