/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-ROI-ROIO-ROIRefWithTag-ROIRefWithTagO+RelativeOidRefWithTag.asn"
 */

#ifndef	_RelativeOidRefWithTag_H_
#define	_RelativeOidRefWithTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <RELATIVE-OID.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RelativeOidRefWithTag */
typedef RELATIVE_OID_t	 RelativeOidRefWithTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelativeOidRefWithTag;
asn_struct_free_f RelativeOidRefWithTag_free;
asn_struct_print_f RelativeOidRefWithTag_print;
asn_constr_check_f RelativeOidRefWithTag_constraint;
ber_type_decoder_f RelativeOidRefWithTag_decode_ber;
der_type_encoder_f RelativeOidRefWithTag_encode_der;
xer_type_decoder_f RelativeOidRefWithTag_decode_xer;
xer_type_encoder_f RelativeOidRefWithTag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RelativeOidRefWithTag_H_ */
#include <asn_internal.h>
