/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IS-ROI-ROIO-ROIRefWithTag-ROIRefWithTagO+RelativeOidRefWithTag.asn"
 */

#ifndef	_SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO_H_
#define	_SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <RELATIVE-OID.h>
#include "RelativeOidRefWithTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IS-ROI-ROIO-ROIRefWithTag-ROIRefWithTagO */
typedef struct SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO {
	struct seq {
		RELATIVE_OID_t	 relativeOid1;
		RELATIVE_OID_t	*relativeOid2	/* OPTIONAL */;
		RelativeOidRefWithTag_t	 relativeOid3;
		RelativeOidRefWithTag_t	*relativeOid4	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IS_ROI_ROIO_ROIRefWithTag_ROIRefWithTagO_H_ */
#include <asn_internal.h>
