/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#include "ChoiceWithExtensible.h"

static asn_TYPE_member_t asn_MBR_ChoiceWithExtensible_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceWithExtensible, choice.a),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceWithExtensible, choice.b),
		(ASN_TAG_CLASS_UNIVERSAL | (9 << 2)),
		0,
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"b"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceWithExtensible, choice.d),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"d"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceWithExtensible, choice.e),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"e"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChoiceWithExtensible_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* d at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* a at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (9 << 2)), 1, 0, 0 }, /* b at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 3, 0, 0 } /* e at 13 */
};
static asn_CHOICE_specifics_t asn_SPC_ChoiceWithExtensible_specs_1 = {
	sizeof(struct ChoiceWithExtensible),
	offsetof(struct ChoiceWithExtensible, _asn_ctx),
	offsetof(struct ChoiceWithExtensible, present),
	sizeof(((struct ChoiceWithExtensible *)0)->present),
	asn_MAP_ChoiceWithExtensible_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChoiceWithExtensible = {
	"ChoiceWithExtensible",
	"ChoiceWithExtensible",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ChoiceWithExtensible_1,
	4,	/* Elements count */
	&asn_SPC_ChoiceWithExtensible_specs_1	/* Additional specs */
};

