/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#ifndef	_ChoiceWithExtensible_H_
#define	_ChoiceWithExtensible_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceWithExtensible_PR {
	ChoiceWithExtensible_PR_NOTHING,	/* No components present */
	ChoiceWithExtensible_PR_a,
	ChoiceWithExtensible_PR_b,
	ChoiceWithExtensible_PR_d,
	ChoiceWithExtensible_PR_e
} ChoiceWithExtensible_PR;

/* ChoiceWithExtensible */
typedef struct ChoiceWithExtensible {
	ChoiceWithExtensible_PR present;
	union ChoiceWithExtensible_u {
		long	 a;
		double	 b;
		BOOLEAN_t	 d;
		long	 e;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceWithExtensible_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceWithExtensible;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceWithExtensible_H_ */
#include <asn_internal.h>
