/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "ForTest.as_n"
 */

#ifndef	_SequenceRecord_FirstExtension_H_
#define	_SequenceRecord_FirstExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-FirstExtension */
typedef struct SequenceRecord_FirstExtension {
	long	 a;
	BOOLEAN_t	*b	/* OPTIONAL */;
	long	*c	/* OPTIONAL */;
	double	 d;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_FirstExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_FirstExtension;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_FirstExtension_H_ */
#include <asn_internal.h>
