/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-IA5D-IA5-IA5D-IA5D.asn"
 */

#ifndef	_SequenceRecord_IA5D_IA5_IA5D_IA5D_H_
#define	_SequenceRecord_IA5D_IA5_IA5D_IA5D_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-IA5D-IA5-IA5D-IA5D */
typedef struct SequenceRecord_IA5D_IA5_IA5D_IA5D {
	IA5String_t	*val1	/* DEFAULT 12"3 */;
	IA5String_t	 val2;
	IA5String_t	*val3	/* DEFAULT 567 */;
	IA5String_t	*val4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_IA5D_IA5_IA5D_IA5D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_IA5D_IA5_IA5D_IA5D;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_IA5D_IA5_IA5D_IA5D_H_ */
#include <asn_internal.h>
