/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-I-IO-I-S-1I-S-1IO-1I.asn"
 */

#include "SequenceRecord-I-IO-I-S-1I-S-1IO-1I.h"

static asn_TYPE_member_t asn_MBR_type4_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct type4, value1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value1"
		},
};
static ber_tlv_tag_t asn_DEF_type4_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_type4_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* value1 at 14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_type4_specs_5 = {
	sizeof(struct type4),
	offsetof(struct type4, _asn_ctx),
	asn_MAP_type4_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type4_5 = {
	"type4",
	"type4",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_type4_tags_5,
	sizeof(asn_DEF_type4_tags_5)
		/sizeof(asn_DEF_type4_tags_5[0]) - 1, /* 1 */
	asn_DEF_type4_tags_5,	/* Same as above */
	sizeof(asn_DEF_type4_tags_5)
		/sizeof(asn_DEF_type4_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_type4_5,
	1,	/* Elements count */
	&asn_SPC_type4_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_type5_7[] = {
	{ ATF_POINTER, 1, offsetof(struct type5, value1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct type5, value2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value2"
		},
};
static ber_tlv_tag_t asn_DEF_type5_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_type5_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* value1 at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value2 at 18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_type5_specs_7 = {
	sizeof(struct type5),
	offsetof(struct type5, _asn_ctx),
	asn_MAP_type5_tag2el_7,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type5_7 = {
	"type5",
	"type5",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_type5_tags_7,
	sizeof(asn_DEF_type5_tags_7)
		/sizeof(asn_DEF_type5_tags_7[0]) - 1, /* 1 */
	asn_DEF_type5_tags_7,	/* Same as above */
	sizeof(asn_DEF_type5_tags_7)
		/sizeof(asn_DEF_type5_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_type5_7,
	2,	/* Elements count */
	&asn_SPC_type5_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, type),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, type2),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, type3),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type3"
		},
	{ ATF_POINTER, 1, offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, type4),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		0,
		&asn_DEF_type4_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, type5),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		0,
		&asn_DEF_type5_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type5"
		},
};
static ber_tlv_tag_t asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 0, 0, 0 }, /* type at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 1, 0, 0 }, /* type2 at 10 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 2, 0, 0 }, /* type3 at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 3, 0, 0 }, /* type4 at 14 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 4, 0, 0 } /* type5 at 16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_specs_1 = {
	sizeof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I),
	offsetof(struct SequenceRecord_I_IO_I_S_1I_S_1IO_1I, _asn_ctx),
	asn_MAP_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I = {
	"SequenceRecord-I-IO-I-S-1I-S-1IO-1I",
	"SequenceRecord-I-IO-I-S-1I-S-1IO-1I",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1,
	sizeof(asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1)
		/sizeof(asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1[0]), /* 1 */
	asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1)
		/sizeof(asn_DEF_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_1,
	5,	/* Elements count */
	&asn_SPC_SequenceRecord_I_IO_I_S_1I_S_1IO_1I_specs_1	/* Additional specs */
};

