/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-DirectRef+DirectRefRecord-S-I-IO-IO+SequenceRecord-I-IO-I-IMPLICIT.asn"
 */

#ifndef	_DirectRefRecord_S_I_IO_I_H_
#define	_DirectRefRecord_S_I_IO_I_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SequenceRecord-I-IO-I.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DirectRefRecord-S-I-IO-I */
typedef SequenceRecord_I_IO_I_t	 DirectRefRecord_S_I_IO_I_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirectRefRecord_S_I_IO_I;
asn_struct_free_f DirectRefRecord_S_I_IO_I_free;
asn_struct_print_f DirectRefRecord_S_I_IO_I_print;
asn_constr_check_f DirectRefRecord_S_I_IO_I_constraint;
ber_type_decoder_f DirectRefRecord_S_I_IO_I_decode_ber;
der_type_encoder_f DirectRefRecord_S_I_IO_I_encode_der;
xer_type_decoder_f DirectRefRecord_S_I_IO_I_decode_xer;
xer_type_encoder_f DirectRefRecord_S_I_IO_I_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DirectRefRecord_S_I_IO_I_H_ */
#include <asn_internal.h>
