/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-DirectRef+DirectRefRecord-S-I-IO-IO+SequenceRecord-I-IO-I-IMPLICIT.asn"
 */

#ifndef	_SequenceRecord_DirectRef_H_
#define	_SequenceRecord_DirectRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DirectRefRecord-S-I-IO-I.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceRecord-DirectRef */
typedef struct SequenceRecord_DirectRef {
	DirectRefRecord_S_I_IO_I_t	 field;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_DirectRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_DirectRef;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceRecord_DirectRef_H_ */
#include <asn_internal.h>
