/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "RefT1+SequenceT2ref+SetT2ref+ChoiceT2ref+SetOfT2ref+SequenceOfT2ref+RefT1refRef.asn"
 */

#ifndef	_ChoiceT2ref_H_
#define	_ChoiceT2ref_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RefT1.h"
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceT2ref_PR {
	ChoiceT2ref_PR_NOTHING,	/* No components present */
	ChoiceT2ref_PR_one,
	ChoiceT2ref_PR_two
} ChoiceT2ref_PR;

/* ChoiceT2ref */
typedef struct ChoiceT2ref {
	ChoiceT2ref_PR present;
	union ChoiceT2ref_u {
		RefT1_t	 one;
		IA5String_t	 two;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceT2ref_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceT2ref;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceT2ref_H_ */
#include <asn_internal.h>
