/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest1"
 * 	found in "RefT1+SequenceT2ref+SetT2ref+ChoiceT2ref+SetOfT2ref+SequenceOfT2ref+RefT1refRef.asn"
 */

#ifndef	_RefT1_H_
#define	_RefT1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RefT1 */
typedef long	 RefT1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RefT1;
asn_struct_free_f RefT1_free;
asn_struct_print_f RefT1_print;
asn_constr_check_f RefT1_constraint;
ber_type_decoder_f RefT1_decode_ber;
der_type_encoder_f RefT1_encode_der;
xer_type_decoder_f RefT1_decode_xer;
xer_type_encoder_f RefT1_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RefT1_H_ */
#include <asn_internal.h>
