/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "RefT1+SequenceT2ref+SetT2ref+ChoiceT2ref+SetOfT2ref+SequenceOfT2ref+RefT1refRef.asn"
 */

#ifndef	_RefT1refRef_H_
#define	_RefT1refRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RefT1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RefT1refRef */
typedef RefT1_t	 RefT1refRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RefT1refRef;
asn_struct_free_f RefT1refRef_free;
asn_struct_print_f RefT1refRef_print;
asn_constr_check_f RefT1refRef_constraint;
ber_type_decoder_f RefT1refRef_decode_ber;
der_type_encoder_f RefT1refRef_encode_der;
xer_type_decoder_f RefT1refRef_decode_xer;
xer_type_encoder_f RefT1refRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RefT1refRef_H_ */
#include <asn_internal.h>
