/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "RefT1+SequenceT2ref+SetT2ref+ChoiceT2ref+SetOfT2ref+SequenceOfT2ref+RefT1refRef.asn"
 */

#ifndef	_SequenceT2ref_H_
#define	_SequenceT2ref_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RefT1.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceT2ref */
typedef struct SequenceT2ref {
	RefT1_t	 one;
	RefT1_t	*two	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceT2ref_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceT2ref;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceT2ref_H_ */
#include <asn_internal.h>
