/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTest2"
 * 	found in "RefT1+SequenceT2ref+SetT2ref+ChoiceT2ref+SetOfT2ref+SequenceOfT2ref+RefT1refRef.asn"
 */

#include "SetT2ref.h"

static asn_TYPE_member_t asn_MBR_SetT2ref_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetT2ref, one),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RefT1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"one"
		},
	{ ATF_POINTER, 1, offsetof(struct SetT2ref, two),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RefT1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"two"
		},
};
static ber_tlv_tag_t asn_DEF_SetT2ref_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SetT2ref_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* one at 20 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* two at 21 */
};
static uint8_t asn_MAP_SetT2ref_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6)
};
static asn_SET_specifics_t asn_SPC_SetT2ref_specs_1 = {
	sizeof(struct SetT2ref),
	offsetof(struct SetT2ref, _asn_ctx),
	offsetof(struct SetT2ref, _presence_map),
	asn_MAP_SetT2ref_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_SetT2ref_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SetT2ref_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SetT2ref = {
	"SetT2ref",
	"SetT2ref",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SetT2ref_tags_1,
	sizeof(asn_DEF_SetT2ref_tags_1)
		/sizeof(asn_DEF_SetT2ref_tags_1[0]), /* 1 */
	asn_DEF_SetT2ref_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetT2ref_tags_1)
		/sizeof(asn_DEF_SetT2ref_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SetT2ref_1,
	2,	/* Elements count */
	&asn_SPC_SetT2ref_specs_1	/* Additional specs */
};

