/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceRecord-ESO-selfRef.asn"
 */

#ifndef	_SequenceRecord_ESO_selfRef_H_
#define	_SequenceRecord_ESO_selfRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceRecord_ESO_selfRef;

/* SequenceRecord-ESO-selfRef */
typedef struct SequenceRecord_ESO_selfRef {
	struct SequenceRecord_ESO_selfRef	*ptr1	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceRecord_ESO_selfRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceRecord_ESO_selfRef;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SequenceRecord-ESO-selfRef.h"

#endif	/* _SequenceRecord_ESO_selfRef_H_ */
#include <asn_internal.h>
