/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "SOME-MODULE"
 * 	found in "SequenceOfSequenceRecord-I-IO-I+SequenceRecord-I-IO-IRef+SequenceRecord-I-IO-I.asn"
 */

#ifndef	_SequenceOfSequenceRecord_I_IO_I_H_
#define	_SequenceOfSequenceRecord_I_IO_I_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceRecord_I_IO_I;

/* SequenceOfSequenceRecord-I-IO-I */
typedef struct SequenceOfSequenceRecord_I_IO_I {
	A_SEQUENCE_OF(struct SequenceRecord_I_IO_I) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfSequenceRecord_I_IO_I_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfSequenceRecord_I_IO_I;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SequenceRecord-I-IO-IRef.h"

#endif	/* _SequenceOfSequenceRecord_I_IO_I_H_ */
#include <asn_internal.h>
